package com.mentor.nucleus.bp.core;
//====================================================================
//
// File:      com.mentor.nucleus.bp.core.DomainAsComponent_c.java
//
// WARNING: Do not edit this generated file
// Generated by ../MC-Java/java.arc, $Revision: 1.111 $
//
// (c) Copyright 2005-2014 by Mentor Graphics Corp.  All rights reserved.
//
//====================================================================

// No special imports
import java.util.*;
import java.lang.reflect.*;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.runtime.IAdaptable;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import com.mentor.nucleus.bp.core.util.PersistenceUtil;
import org.eclipse.core.runtime.NullProgressMonitor;
import com.mentor.nucleus.bp.core.ui.marker.UmlProblem;
import com.mentor.nucleus.bp.core.common.*;
abstract class EV_DOMAIN_AS_COMPONENT extends genericEvent_c {
	public abstract int getEvtcode();
}

public class DomainAsComponent_c extends NonRootModelElement
		implements
			IAdaptable,
			Cloneable {
	// Public Constructors
	public DomainAsComponent_c(ModelRoot modelRoot, java.util.UUID p_m_id,
			java.util.UUID p_m_dom_id) {
		super(modelRoot);
		//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
		m_dom_id = IdAssigner.preprocessUUID(p_m_dom_id);
		//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
		m_id = IdAssigner.preprocessUUID(p_m_id);

		Object[] key = {m_dom_id, m_id};
		addInstanceToMap(key);
	}
	static public DomainAsComponent_c createProxy(ModelRoot modelRoot,
			java.util.UUID p_m_id, java.util.UUID p_m_dom_id,
			String p_contentPath, IPath p_localPath) {
		ModelRoot resolvedModelRoot = ModelRoot.findModelRoot(modelRoot,
				p_contentPath, p_localPath);
		// if a model root was not resolved it is most likely
		// due to a missing file of the proxy, defualt back to
		// the original model root
		if (resolvedModelRoot != null)
			modelRoot = resolvedModelRoot;
		InstanceList instances = modelRoot
				.getInstanceList(DomainAsComponent_c.class);
		DomainAsComponent_c new_inst = null;
		synchronized (instances) {
			Object[] key = {p_m_dom_id, p_m_id};
			new_inst = (DomainAsComponent_c) instances.get(key);
		}
		String contentPath = PersistenceUtil.resolveRelativePath(p_localPath,
				new Path(p_contentPath));
		if (modelRoot.isNewCompareRoot()) {
			// for comparisons we do not want to change
			// the content path
			contentPath = p_contentPath;
		}
		if (new_inst != null && !modelRoot.isCompareRoot()) {
			PersistableModelComponent pmc = new_inst.getPersistableComponent();
			if (pmc == null) {
				// dangling reference, redo this instance
				new_inst.batchUnrelate();
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				new_inst.m_dom_id = IdAssigner.preprocessUUID(p_m_dom_id);
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				new_inst.m_id = IdAssigner.preprocessUUID(p_m_id);

			}
		}
		if (new_inst == null) {
			// there is no instance matching the id, create a proxy
			// if the resource doesn't exist then this will be a dangling reference
			new_inst = new DomainAsComponent_c(modelRoot, p_m_id, p_m_dom_id);
			new_inst.m_contentPath = contentPath;
		}
		return new_inst;
	}

	static public DomainAsComponent_c resolveInstance(ModelRoot modelRoot,
			java.util.UUID p_m_id, java.util.UUID p_m_dom_id) {
		InstanceList instances = modelRoot
				.getInstanceList(DomainAsComponent_c.class);
		DomainAsComponent_c source = null;
		synchronized (instances) {
			Object[] key = {p_m_dom_id, p_m_id};
			source = (DomainAsComponent_c) instances.get(key);
			if (source != null && !modelRoot.isCompareRoot()) {
				source.convertFromProxy();
				source.batchUnrelate();
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				source.m_dom_id = IdAssigner.preprocessUUID(p_m_dom_id);
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				source.m_id = IdAssigner.preprocessUUID(p_m_id);

				return source;
			}
		}
		// there is no instance matching the id
		DomainAsComponent_c new_inst = new DomainAsComponent_c(modelRoot,
				p_m_id, p_m_dom_id);
		return new_inst;
	}
	public DomainAsComponent_c(ModelRoot modelRoot) {
		super(modelRoot);
		m_dom_id = IdAssigner.NULL_UUID;
		m_id = IdAssigner.NULL_UUID;
		Object[] key = {m_dom_id, m_id};
		addInstanceToMap(key);
	}

	public Object getInstanceKey() {
		Object[] key = {m_dom_id, m_id};
		return key;
	}

	public boolean setInstanceKey(UUID p_newKey) {

		boolean changed = false;
		// round p1
		// round p2
		// round p3
		// round p4
		// round p5
		if (m_dom_id != p_newKey) {

			m_dom_id = p_newKey;
			changed = true;
		}
		return changed;
	}

	public boolean equals(Object elem) {
		if (!(elem instanceof DomainAsComponent_c)) {
			return false;
		}
		// check that the model-roots are the same
		if (((NonRootModelElement) elem).getModelRoot() != getModelRoot()) {
			return false;
		}

		return identityEquals(elem);
	}

	public boolean identityEquals(Object elem) {
		if (!(elem instanceof DomainAsComponent_c)) {
			return false;
		}

		DomainAsComponent_c me = (DomainAsComponent_c) elem;
		// don't allow an empty id-value to produce a false positive result;
		// in this case, use whether the two instances are actually the same 
		// one in memory, instead
		if ((IdAssigner.NULL_UUID.equals(getDom_id()) || IdAssigner.NULL_UUID
				.equals(((DomainAsComponent_c) elem).getDom_id()))
				&& this != elem) {
			return false;
		}
		if (!getDom_id().equals(((DomainAsComponent_c) elem).getDom_id()))
			return false;
		// don't allow an empty id-value to produce a false positive result;
		// in this case, use whether the two instances are actually the same 
		// one in memory, instead
		if ((IdAssigner.NULL_UUID.equals(getId()) || IdAssigner.NULL_UUID
				.equals(((DomainAsComponent_c) elem).getId())) && this != elem) {
			return false;
		}
		if (!getId().equals(((DomainAsComponent_c) elem).getId()))
			return false;
		return true;
	}

	public boolean cachedIdentityEquals(Object elem) {
		if (!(elem instanceof DomainAsComponent_c)) {
			return false;
		}

		DomainAsComponent_c me = (DomainAsComponent_c) elem;
		if (!getDom_idCachedValue().equals(
				((DomainAsComponent_c) elem).getDom_idCachedValue()))
			return false;
		if (!getIdCachedValue().equals(
				((DomainAsComponent_c) elem).getIdCachedValue()))
			return false;
		return true;
	}

	// Attributes
	private java.util.UUID m_dom_id;
	private java.util.UUID m_id;

	// declare association references from this class

	// referring navigation

	Domain_c HasSubjectMatterOfDomain;
	public void relateAcrossR4204To(Domain_c target) {
		relateAcrossR4204To(target, true);
	}
	public void relateAcrossR4204To(Domain_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (target == HasSubjectMatterOfDomain)
			return; // already related

		if (HasSubjectMatterOfDomain != target) {

			Object oldKey = getInstanceKey();

			if (HasSubjectMatterOfDomain != null) {

				HasSubjectMatterOfDomain.clearBackPointerR4204To(this);

				if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) { //$NON-NLS-1$
					Ooaofooa.log
							.println(
									ILogger.CONSISTENCY,
									"DomainAsComponent_c.relateAcrossR4204To(Domain_c target)",
									"Relate performed across R4204 from Domain As Component to Domain without unrelate of prior instance.");
				}
			}

			HasSubjectMatterOfDomain = target;
			m_dom_id = target.getDom_id();
			updateInstanceKey(oldKey, getInstanceKey());
			target.setBackPointerR4204To(this);
			target.addRef();
			if (notifyChanges) {
				RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(
						Modeleventnotification_c.DELTA_ELEMENT_RELATED, this,
						target, "4204", "");
				Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(
						change);
			}
		}
	}
	public void unrelateAcrossR4204From(Domain_c target) {
		unrelateAcrossR4204From(target, true);
	}
	public void unrelateAcrossR4204From(Domain_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (HasSubjectMatterOfDomain == null)
			return; // already unrelated

		if (target != HasSubjectMatterOfDomain) {
			Exception e = new Exception();
			e.fillInStackTrace();
			CorePlugin.logError(
					"Tried to unrelate from non-related instance across R4204",
					e);
			return;
		}

		if (target != null) {
			target.clearBackPointerR4204To(this);
		}

		if (HasSubjectMatterOfDomain != null) {

			m_dom_id = HasSubjectMatterOfDomain.getDom_id();
			HasSubjectMatterOfDomain = null;
			target.removeRef();
			if (notifyChanges) {
				RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(
						Modeleventnotification_c.DELTA_ELEMENT_UNRELATED, this,
						target, "4204", "");
				Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(
						change);
			}
		}
	}

	// referring navigation

	Component_c DefinedSubjectMatterForComponent;
	public void relateAcrossR4204To(Component_c target) {
		relateAcrossR4204To(target, true);
	}
	public void relateAcrossR4204To(Component_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (target == DefinedSubjectMatterForComponent)
			return; // already related

		if (DefinedSubjectMatterForComponent != target) {

			Object oldKey = getInstanceKey();

			if (DefinedSubjectMatterForComponent != null) {

				DefinedSubjectMatterForComponent.clearBackPointerR4204To(this);

				if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) { //$NON-NLS-1$
					Ooaofooa.log
							.println(
									ILogger.CONSISTENCY,
									"DomainAsComponent_c.relateAcrossR4204To(Component_c target)",
									"Relate performed across R4204 from Domain As Component to Component without unrelate of prior instance.");
				}
			}

			DefinedSubjectMatterForComponent = target;
			if (IdAssigner.NULL_UUID.equals(target.getId())) {
				// do not update cached value
			} else {
				// update cached value
				m_id = target.getIdCachedValue();
			}
			updateInstanceKey(oldKey, getInstanceKey());
			target.setBackPointerR4204To(this);
			target.addRef();
			if (notifyChanges) {
				RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(
						Modeleventnotification_c.DELTA_ELEMENT_RELATED, this,
						target, "4204", "");
				Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(
						change);
			}
		}
	}
	public void unrelateAcrossR4204From(Component_c target) {
		unrelateAcrossR4204From(target, true);
	}
	public void unrelateAcrossR4204From(Component_c target,
			boolean notifyChanges) {
		if (target == null)
			return;

		if (DefinedSubjectMatterForComponent == null)
			return; // already unrelated

		if (target != DefinedSubjectMatterForComponent) {
			Exception e = new Exception();
			e.fillInStackTrace();
			CorePlugin.logError(
					"Tried to unrelate from non-related instance across R4204",
					e);
			return;
		}

		if (target != null) {
			target.clearBackPointerR4204To(this);
		}

		if (DefinedSubjectMatterForComponent != null) {

			m_id = DefinedSubjectMatterForComponent.getId();
			if (IdAssigner.NULL_UUID.equals(m_id)) {
				m_id = DefinedSubjectMatterForComponent.getIdCachedValue();
			}
			DefinedSubjectMatterForComponent = null;
			target.removeRef();
			if (notifyChanges) {
				RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(
						Modeleventnotification_c.DELTA_ELEMENT_UNRELATED, this,
						target, "4204", "");
				Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(
						change);
			}
		}
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Domain_c[] targets) {
		return getOneCN_DCOnR4204(targets, null);
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Domain_c[] targets,
			ClassQueryInterface_c test) {
		DomainAsComponent_c ret_val = null;
		if (targets != null) {
			for (int i = 0; i < targets.length && ret_val == null; ++i) {
				ret_val = getOneCN_DCOnR4204(targets[i], test);
			}
		}

		return ret_val;
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Domain_c target) {
		return getOneCN_DCOnR4204(target, null);
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Domain_c target,
			boolean loadComponent) {
		return getOneCN_DCOnR4204(target.getModelRoot(), target, null,
				loadComponent);
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Domain_c target,
			ClassQueryInterface_c test) {
		if (target != null) {
			return getOneCN_DCOnR4204(target.getModelRoot(), target, test);
		}
		return null;
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(ModelRoot modelRoot,
			Domain_c target, ClassQueryInterface_c test) {
		return getOneCN_DCOnR4204(modelRoot, target, test, true);
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(ModelRoot modelRoot,
			Domain_c target, ClassQueryInterface_c test, boolean loadComponent) {
		return find_getOneCN_DCOnR4204(modelRoot, target, test);
	}
	private static DomainAsComponent_c find_getOneCN_DCOnR4204(
			ModelRoot modelRoot, Domain_c target, ClassQueryInterface_c test) {
		if (target != null) {
			synchronized (target.backPointer_DefinedSubjectMatterForDomainAsComponentDefinedSubjectMatterFor_R4204) {
				for (int i = 0; i < target.backPointer_DefinedSubjectMatterForDomainAsComponentDefinedSubjectMatterFor_R4204
						.size(); ++i) {
					DomainAsComponent_c source = (DomainAsComponent_c) target.backPointer_DefinedSubjectMatterForDomainAsComponentDefinedSubjectMatterFor_R4204
							.get(i);
					if (source != null
							&& (test == null || test.evaluate(source))) {
						return source;
					}
				}
			}
		}
		// not found
		return null;
	}

	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(Domain_c[] targets) {
		return getManyCN_DCsOnR4204(targets, null);
	}
	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(
			Domain_c[] targets, boolean loadComponent) {
		return getManyCN_DCsOnR4204(targets, null, loadComponent);
	}
	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(
			Domain_c[] targets, ClassQueryInterface_c test) {
		return getManyCN_DCsOnR4204(targets, test, true);
	}

	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(
			Domain_c[] targets, ClassQueryInterface_c test,
			boolean loadComponent) {

		if (targets == null || targets.length == 0 || targets[0] == null)
			return new DomainAsComponent_c[0];

		ModelRoot modelRoot = targets[0].getModelRoot();

		InstanceList instances = modelRoot
				.getInstanceList(DomainAsComponent_c.class);

		Vector matches = new Vector();
		for (int i = 0; i < targets.length; i++) {
			synchronized (targets[i].backPointer_DefinedSubjectMatterForDomainAsComponentDefinedSubjectMatterFor_R4204) {
				for (int j = 0; j < targets[i].backPointer_DefinedSubjectMatterForDomainAsComponentDefinedSubjectMatterFor_R4204
						.size(); ++j) {
					DomainAsComponent_c source = (DomainAsComponent_c) targets[i].backPointer_DefinedSubjectMatterForDomainAsComponentDefinedSubjectMatterFor_R4204
							.get(j);
					if (source != null
							&& (test == null || test.evaluate(source))) {
						matches.add(source);
					}
				}
			}
		}
		if (matches.size() > 0) {
			DomainAsComponent_c[] ret_set = new DomainAsComponent_c[matches
					.size()];
			matches.copyInto(ret_set);
			return ret_set;
		} else {
			return new DomainAsComponent_c[0];
		}
	}

	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(Domain_c target) {
		if (target != null) {
			Domain_c[] targetArray = new Domain_c[1];
			targetArray[0] = target;
			return getManyCN_DCsOnR4204(targetArray);
		} else {
			DomainAsComponent_c[] result = new DomainAsComponent_c[0];
			return result;
		}
	}

	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(Domain_c target,
			boolean loadComponent) {
		if (target != null) {
			Domain_c[] targetArray = new Domain_c[1];
			targetArray[0] = target;
			return getManyCN_DCsOnR4204(targetArray, loadComponent);
		} else {
			DomainAsComponent_c[] result = new DomainAsComponent_c[0];
			return result;
		}
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Component_c[] targets) {
		return getOneCN_DCOnR4204(targets, null);
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Component_c[] targets,
			ClassQueryInterface_c test) {
		DomainAsComponent_c ret_val = null;
		if (targets != null) {
			for (int i = 0; i < targets.length && ret_val == null; ++i) {
				ret_val = getOneCN_DCOnR4204(targets[i], test);
			}
		}

		return ret_val;
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Component_c target) {
		return getOneCN_DCOnR4204(target, null);
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Component_c target,
			boolean loadComponent) {
		return getOneCN_DCOnR4204(target.getModelRoot(), target, null,
				loadComponent);
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(Component_c target,
			ClassQueryInterface_c test) {
		if (target != null) {
			return getOneCN_DCOnR4204(target.getModelRoot(), target, test);
		}
		return null;
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(ModelRoot modelRoot,
			Component_c target, ClassQueryInterface_c test) {
		return getOneCN_DCOnR4204(modelRoot, target, test, true);
	}

	public static DomainAsComponent_c getOneCN_DCOnR4204(ModelRoot modelRoot,
			Component_c target, ClassQueryInterface_c test,
			boolean loadComponent) {
		return find_getOneCN_DCOnR4204(modelRoot, target, test);
	}
	private static DomainAsComponent_c find_getOneCN_DCOnR4204(
			ModelRoot modelRoot, Component_c target, ClassQueryInterface_c test) {
		if (target != null) {
			synchronized (target.backPointer_HasSubjectMatterOfDomainAsComponentHasSubjectMatterOf_R4204) {
				for (int i = 0; i < target.backPointer_HasSubjectMatterOfDomainAsComponentHasSubjectMatterOf_R4204
						.size(); ++i) {
					DomainAsComponent_c source = (DomainAsComponent_c) target.backPointer_HasSubjectMatterOfDomainAsComponentHasSubjectMatterOf_R4204
							.get(i);
					if (source != null
							&& (test == null || test.evaluate(source))) {
						return source;
					}
				}
			}
		}
		// not found
		return null;
	}

	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(
			Component_c[] targets) {
		return getManyCN_DCsOnR4204(targets, null);
	}
	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(
			Component_c[] targets, boolean loadComponent) {
		return getManyCN_DCsOnR4204(targets, null, loadComponent);
	}
	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(
			Component_c[] targets, ClassQueryInterface_c test) {
		return getManyCN_DCsOnR4204(targets, test, true);
	}

	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(
			Component_c[] targets, ClassQueryInterface_c test,
			boolean loadComponent) {

		if (targets == null || targets.length == 0 || targets[0] == null)
			return new DomainAsComponent_c[0];

		ModelRoot modelRoot = targets[0].getModelRoot();

		InstanceList instances = modelRoot
				.getInstanceList(DomainAsComponent_c.class);

		Vector matches = new Vector();
		for (int i = 0; i < targets.length; i++) {
			synchronized (targets[i].backPointer_HasSubjectMatterOfDomainAsComponentHasSubjectMatterOf_R4204) {
				for (int j = 0; j < targets[i].backPointer_HasSubjectMatterOfDomainAsComponentHasSubjectMatterOf_R4204
						.size(); ++j) {
					DomainAsComponent_c source = (DomainAsComponent_c) targets[i].backPointer_HasSubjectMatterOfDomainAsComponentHasSubjectMatterOf_R4204
							.get(j);
					if (source != null
							&& (test == null || test.evaluate(source))) {
						matches.add(source);
					}
				}
			}
		}
		if (matches.size() > 0) {
			DomainAsComponent_c[] ret_set = new DomainAsComponent_c[matches
					.size()];
			matches.copyInto(ret_set);
			return ret_set;
		} else {
			return new DomainAsComponent_c[0];
		}
	}

	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(Component_c target) {
		if (target != null) {
			Component_c[] targetArray = new Component_c[1];
			targetArray[0] = target;
			return getManyCN_DCsOnR4204(targetArray);
		} else {
			DomainAsComponent_c[] result = new DomainAsComponent_c[0];
			return result;
		}
	}

	public static DomainAsComponent_c[] getManyCN_DCsOnR4204(
			Component_c target, boolean loadComponent) {
		if (target != null) {
			Component_c[] targetArray = new Component_c[1];
			targetArray[0] = target;
			return getManyCN_DCsOnR4204(targetArray, loadComponent);
		} else {
			DomainAsComponent_c[] result = new DomainAsComponent_c[0];
			return result;
		}
	}

	public void batchRelate(ModelRoot modelRoot, boolean notifyChanges,
			boolean searchAllRoots) {
		batchRelate(modelRoot, false, notifyChanges, searchAllRoots);
	}

	public void batchRelate(ModelRoot modelRoot, boolean relateProxies,
			boolean notifyChanges, boolean searchAllRoots) {
		InstanceList instances = null;
		ModelRoot baseRoot = modelRoot;

		// R4204
		Domain_c relInst55661 = (Domain_c) baseRoot.getInstanceList(
				Domain_c.class).get(new Object[]{m_dom_id});
		// if there was no local element, check for any global elements
		// failing that proceed to check other model roots
		if (relInst55661 == null) {
			relInst55661 = (Domain_c) Ooaofooa.getDefaultInstance()
					.getInstanceList(Domain_c.class)
					.get(new Object[]{m_dom_id});
		}
		if (relInst55661 == null && searchAllRoots && !baseRoot.isCompareRoot()) {
			Ooaofooa[] roots = Ooaofooa.getInstances();
			for (int i = 0; i < roots.length; i++) {
				if (roots[i].isCompareRoot()) {
					// never use elements from any compare root
					continue;
				}
				relInst55661 = (Domain_c) roots[i].getInstanceList(
						Domain_c.class).get(new Object[]{m_dom_id});
				if (relInst55661 != null)
					break;
			}
		}
		//synchronized
		if (relInst55661 != null) {
			if (relateProxies || !isProxy()
					|| (inSameComponent(this, relInst55661) && !isProxy())) {
				relInst55661.relateAcrossR4204To(this, notifyChanges);
			}
		}

		Component_c relInst55662 = (Component_c) baseRoot.getInstanceList(
				Component_c.class).get(new Object[]{m_id});
		// if there was no local element, check for any global elements
		// failing that proceed to check other model roots
		if (relInst55662 == null) {
			relInst55662 = (Component_c) Ooaofooa.getDefaultInstance()
					.getInstanceList(Component_c.class).get(new Object[]{m_id});
		}
		if (relInst55662 == null && searchAllRoots && !baseRoot.isCompareRoot()) {
			Ooaofooa[] roots = Ooaofooa.getInstances();
			for (int i = 0; i < roots.length; i++) {
				if (roots[i].isCompareRoot()) {
					// never use elements from any compare root
					continue;
				}
				relInst55662 = (Component_c) roots[i].getInstanceList(
						Component_c.class).get(new Object[]{m_id});
				if (relInst55662 != null)
					break;
			}
		}
		//synchronized
		if (relInst55662 != null) {
			if (relateProxies || !isProxy()
					|| (inSameComponent(this, relInst55662) && !isProxy())) {
				relInst55662.relateAcrossR4204To(this, notifyChanges);
			}
		}

	}
	public void batchUnrelate(boolean notifyChanges) {
		NonRootModelElement inst = null;
		// R4204
		// S_DOM
		inst = HasSubjectMatterOfDomain;
		unrelateAcrossR4204From(HasSubjectMatterOfDomain, notifyChanges);
		if (inst != null) {
			inst.removeRef();
		}
		// C_C
		inst = DefinedSubjectMatterForComponent;
		unrelateAcrossR4204From(DefinedSubjectMatterForComponent, notifyChanges);
		if (inst != null) {
			inst.removeRef();
		}
	}
	public static void batchRelateAll(ModelRoot modelRoot,
			boolean notifyChanges, boolean searchAllRoots) {
		batchRelateAll(modelRoot, notifyChanges, searchAllRoots, false);
	}
	public static void batchRelateAll(ModelRoot modelRoot, boolean notifyChanges, boolean searchAllRoots, boolean relateProxies)
  {
	InstanceList instances = modelRoot.getInstanceList(DomainAsComponent_c.class);
    synchronized(instances) {
        Iterator<NonRootModelElement> cursor = instances.iterator() ;
    	while (cursor.hasNext())
	    {
            final DomainAsComponent_c inst = (DomainAsComponent_c)cursor.next() ;
	        inst.batchRelate(modelRoot, relateProxies, notifyChanges, searchAllRoots );
	    }
	}
  }
	public static void clearInstances(ModelRoot modelRoot) {
		InstanceList instances = modelRoot
				.getInstanceList(DomainAsComponent_c.class);
		synchronized (instances) {
			for (int i = instances.size() - 1; i >= 0; i--) {
				((NonRootModelElement) instances.get(i)).delete_unchecked();
			}

		}
	}

	public static DomainAsComponent_c DomainAsComponentInstance(
			ModelRoot modelRoot, ClassQueryInterface_c test,
			boolean loadComponent) {
		DomainAsComponent_c result = findDomainAsComponentInstance(modelRoot,
				test, loadComponent);
		if (result == null && loadComponent) {
			List pmcs = PersistenceManager.findAllComponents(modelRoot,
					DomainAsComponent_c.class);
			for (int i = 0; i < pmcs.size(); i++) {
				PersistableModelComponent component = (PersistableModelComponent) pmcs
						.get(i);
				if (!component.isLoaded()) {
					try {
						component.load(new NullProgressMonitor());
						result = findDomainAsComponentInstance(modelRoot, test,
								loadComponent);
						if (result != null)
							return result;
					} catch (Exception e) {
						CorePlugin.logError("Error Loading component", e);
					}
				}
			}
		}
		if (result != null && loadComponent) {
			result.loadProxy();
		}
		return result;
	}
	private static DomainAsComponent_c findDomainAsComponentInstance(
			ModelRoot modelRoot, ClassQueryInterface_c test,
			boolean loadComponent) {
		InstanceList instances = modelRoot
				.getInstanceList(DomainAsComponent_c.class);
		synchronized (instances) {
			for (int i = 0; i < instances.size(); ++i) {
				DomainAsComponent_c x = (DomainAsComponent_c) instances.get(i);
				if (test == null || test.evaluate(x)) {
					if (x.ensureLoaded(loadComponent))
						return x;
				}
			}
		}
		return null;
	}
	public static DomainAsComponent_c DomainAsComponentInstance(
			ModelRoot modelRoot, ClassQueryInterface_c test) {
		return DomainAsComponentInstance(modelRoot, test, true);
	}

	public static DomainAsComponent_c DomainAsComponentInstance(
			ModelRoot modelRoot) {
		return DomainAsComponentInstance(modelRoot, null, true);
	}

	public static DomainAsComponent_c[] DomainAsComponentInstances(
			ModelRoot modelRoot, ClassQueryInterface_c test,
			boolean loadComponent) {
		if (loadComponent) {
			PersistenceManager.ensureAllInstancesLoaded(modelRoot,
					DomainAsComponent_c.class);
		}
		InstanceList instances = modelRoot
				.getInstanceList(DomainAsComponent_c.class);
		Vector matches = new Vector();
		synchronized (instances) {
			for (int i = 0; i < instances.size(); ++i) {
				DomainAsComponent_c x = (DomainAsComponent_c) instances.get(i);
				if (test == null || test.evaluate(x)) {
					if (x.ensureLoaded(loadComponent))
						matches.add(x);
				}
			}
			if (matches.size() > 0) {
				DomainAsComponent_c[] ret_set = new DomainAsComponent_c[matches
						.size()];
				matches.copyInto(ret_set);
				return ret_set;
			} else {
				return new DomainAsComponent_c[0];
			}
		}
	}
	public static DomainAsComponent_c[] DomainAsComponentInstances(
			ModelRoot modelRoot, ClassQueryInterface_c test) {
		return DomainAsComponentInstances(modelRoot, test, true);
	}
	public static DomainAsComponent_c[] DomainAsComponentInstances(
			ModelRoot modelRoot) {
		return DomainAsComponentInstances(modelRoot, null, true);
	}

	public boolean delete() {
		boolean result = super.delete();
		boolean delete_error = false;
		String errorMsg = "The following relationships were not torn down by the Domain As Component.dispose call: ";
		Component_c testR4204Inst = Component_c.getOneC_COnR4204(this, false);

		if (testR4204Inst != null) {
			delete_error = true;
			errorMsg = errorMsg + "4204 ";
		}

		Domain_c testR4204InstOth = Domain_c.getOneS_DOMOnR4204(this, false);

		if (testR4204InstOth != null) {
			delete_error = true;
			errorMsg = errorMsg + "4204 ";
		}
		if (delete_error == true) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log.println(ILogger.DELETE, "Domain As Component",
						errorMsg);
			} else {
				Exception e = new Exception();
				e.fillInStackTrace();
				CorePlugin.logError(errorMsg, e);
			}
		}
		return result;
	}

	// end declare instance pool

	// declare attribute accessors
	public boolean isUUID(String attributeName) {
		if (attributeName.equals("dom_id")) {
			return true;
		}
		if (attributeName.equals("id")) {
			return true;
		}
		return false;
	}
	public String getCompUniqueID() {
		UUID tempID = null;
		long longID = 0L;
		StringBuffer result = new StringBuffer();

		tempID = getDom_id();

		if (IdAssigner.NULL_UUID.equals(tempID))
			tempID = getDom_idCachedValue();
		result.append(Long.toHexString(tempID.getMostSignificantBits()));
		result.append(Long.toHexString(tempID.getLeastSignificantBits()));
		tempID = getId();

		if (IdAssigner.NULL_UUID.equals(tempID))
			tempID = getIdCachedValue();
		result.append(Long.toHexString(tempID.getMostSignificantBits()));
		result.append(Long.toHexString(tempID.getLeastSignificantBits()));
		return result.toString();
	}
	// declare attribute accessors
	public long getDom_idLongBased() {
		if (HasSubjectMatterOfDomain != null) {
			return HasSubjectMatterOfDomain.getDom_idLongBased();
		}
		return 0;
	}
	public java.util.UUID getDom_id() {
		if (HasSubjectMatterOfDomain != null) {
			return HasSubjectMatterOfDomain.getDom_id();
		}
		return IdAssigner.NULL_UUID;
	}

	public java.util.UUID getDom_idCachedValue() {
		if (!IdAssigner.NULL_UUID.equals(m_dom_id))
			return m_dom_id;
		else
			return getDom_id();
	}

	public void setDom_id(java.util.UUID newValue) {
		if (newValue != null) {
			if (newValue.equals(m_dom_id)) {
				return;
			}
		} else if (m_dom_id != null) {
			if (m_dom_id.equals(newValue)) {
				return;
			}
		} else {
			return;
		}
		AttributeChangeModelDelta change = new AttributeChangeModelDelta(
				Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this,
				"Dom_id", m_dom_id, newValue, true);
		m_dom_id = IdAssigner.preprocessUUID(newValue);
		Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
	}
	public long getIdLongBased() {
		if (DefinedSubjectMatterForComponent != null) {
			return DefinedSubjectMatterForComponent.getIdLongBased();
		}
		return 0;
	}
	public java.util.UUID getId() {
		if (DefinedSubjectMatterForComponent != null) {
			return DefinedSubjectMatterForComponent.getId();
		}
		return IdAssigner.NULL_UUID;
	}

	public java.util.UUID getIdCachedValue() {
		if (!IdAssigner.NULL_UUID.equals(m_id))
			return m_id;
		else
			return getId();
	}

	public void setId(java.util.UUID newValue) {
		if (newValue != null) {
			if (newValue.equals(m_id)) {
				return;
			}
		} else if (m_id != null) {
			if (m_id.equals(newValue)) {
				return;
			}
		} else {
			return;
		}
		AttributeChangeModelDelta change = new AttributeChangeModelDelta(
				Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this, "Id",
				m_id, newValue, true);
		m_id = IdAssigner.preprocessUUID(newValue);
		Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
	}
	// end declare accessors
	public static void checkClassConsistency(ModelRoot modelRoot) {
		Ooaofooa.log
				.println(ILogger.OPERATION, "Domain As Component", //$NON-NLS-1$
						" Operation entered: Domain As Component::checkClassConsistency"); //$NON-NLS-1$
		if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) { //$NON-NLS-1$
			return;
		}
		DomainAsComponent_c[] objs = DomainAsComponent_c
				.DomainAsComponentInstances(modelRoot, null, false);

		for (int i = 0; i < objs.length; i++) {
			objs[i].checkConsistency();
		}
	}
	public boolean checkConsistency() {
		Ooaofooa.log.println(ILogger.OPERATION, "Domain As Component", //$NON-NLS-1$
				" Operation entered: Domain As Component::checkConsistency"); //$NON-NLS-1$
		if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) { //$NON-NLS-1$
			return true;
		}
		ModelRoot modelRoot = getModelRoot();
		boolean retval = true;
		class DomainAsComponent_c_test55664_c implements ClassQueryInterface_c {
			DomainAsComponent_c_test55664_c(java.util.UUID p55665,
					java.util.UUID p55666) {
				m_p55665 = p55665;
				m_p55666 = p55666;
			}
			private java.util.UUID m_p55665;
			private java.util.UUID m_p55666;
			public boolean evaluate(Object candidate) {
				DomainAsComponent_c selected = (DomainAsComponent_c) candidate;
				boolean retval = false;
				retval = (selected.getDom_id().equals(m_p55665))
						& (selected.getId().equals(m_p55666));
				return retval;
			}
		}

		DomainAsComponent_c[] objs55663 = DomainAsComponent_c
				.DomainAsComponentInstances(modelRoot,
						new DomainAsComponent_c_test55664_c(getDom_id(),
								getId()));

		if (((objs55663.length) == 0)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(ILogger.CONSISTENCY,
								"Domain As Component", //$NON-NLS-1$
								"Consistency: Object: Domain As Component: Cardinality of an identifier is zero. " //$NON-NLS-1$
										+ "Actual Value: " + Integer.toString(objs55663.length)); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: Domain As Component: Cardinality of an identifier is zero. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs55663.length), e);
			}
			retval = false;

		}

		if (((objs55663.length) > 1)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(ILogger.CONSISTENCY,
								"Domain As Component", //$NON-NLS-1$
								"Consistency: Object: Domain As Component: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$
										+ "Actual Value: " //$NON-NLS-1$ 
										+ Integer.toString(objs55663.length)
										+ " Dom_ID: " + "Not Printable" + " Id: " + "Not Printable"); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: Domain As Component: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs55663.length)
										+ " Dom_ID: " + "Not Printable" + " Id: " + "Not Printable", e); //$NON-NLS-1$
			}
			retval = false;

		}

		// Domain As Component is a link class in association: rel.Numb = 4204
		// The one side class in the association is: Component
		class Component_c_test55670_c implements ClassQueryInterface_c {
			Component_c_test55670_c(java.util.UUID p55671) {
				m_p55671 = p55671;
			}
			private java.util.UUID m_p55671;
			public boolean evaluate(Object candidate) {
				Component_c selected = (Component_c) candidate;
				boolean retval = false;
				retval = (selected.getId().equals(m_p55671));
				return retval;
			}
		}

		Component_c[] objs55669 = Component_c.ComponentInstances(modelRoot,
				new Component_c_test55670_c(getId()));

		if (((objs55669.length) > 1)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(ILogger.CONSISTENCY,
								"Domain As Component", //$NON-NLS-1$
								"Consistency: Object: Domain As Component: Association: 4204: Cardinality of one side of link is greater than 1. " //$NON-NLS-1$
										+ "Actual Value: " + Integer.toString(objs55669.length)); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: Domain As Component: Association: 4204: Cardinality of one side of link is greater than 1. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs55669.length), e);
			}
			retval = false;

		}

		// Other side
		// The other side class in the association is: Domain
		class Domain_c_test55673_c implements ClassQueryInterface_c {
			Domain_c_test55673_c(java.util.UUID p55674) {
				m_p55674 = p55674;
			}
			private java.util.UUID m_p55674;
			public boolean evaluate(Object candidate) {
				Domain_c selected = (Domain_c) candidate;
				boolean retval = false;
				retval = (selected.getDom_id().equals(m_p55674));
				return retval;
			}
		}

		Domain_c[] objs55672 = Domain_c.DomainInstances(modelRoot,
				new Domain_c_test55673_c(getDom_id()));

		if (((objs55672.length) > 1)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(ILogger.CONSISTENCY,
								"Domain As Component", //$NON-NLS-1$
								"Consistency: Object: Domain As Component: Association: 4204: Cardinality of other side of link is greater than 1. " //$NON-NLS-1$
										+ "Actual Value: " + Integer.toString(objs55672.length)); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: Domain As Component: Association: 4204: Cardinality of other side of link is greater than 1. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs55672.length), e);
			}
			retval = false;

		}

		return retval;
	}

	public Object getAdapter(Class adapter) {
		Object superAdapter = super.getAdapter(adapter);
		if (superAdapter != null) {
			return superAdapter;
		}
		return null;
	}
} // end Domain As Component
