package com.mentor.nucleus.bp.core;
//====================================================================
//
// File:      com.mentor.nucleus.bp.core.MessageInCommunication_c.java
//
// WARNING: Do not edit this generated file
// Generated by ../MC-Java/java.arc, $Revision: 1.111 $
//
// (c) Copyright 2005-2014 by Mentor Graphics Corp.  All rights reserved.
//
//====================================================================

// No special imports
import java.util.*;
import java.lang.reflect.*;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.runtime.IAdaptable;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import com.mentor.nucleus.bp.core.util.PersistenceUtil;
import org.eclipse.core.runtime.NullProgressMonitor;
import com.mentor.nucleus.bp.core.ui.marker.UmlProblem;
import com.mentor.nucleus.bp.core.common.*;
abstract class EV_MESSAGE_IN_COMMUNICATION extends genericEvent_c {
	public abstract int getEvtcode();
}

public class MessageInCommunication_c extends NonRootModelElement
		implements
			IAdaptable,
			Cloneable {
	// Public Constructors
	public MessageInCommunication_c(ModelRoot modelRoot,
			java.util.UUID p_m_package_id, java.util.UUID p_m_msg_id) {
		super(modelRoot);
		//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
		m_package_id = IdAssigner.preprocessUUID(p_m_package_id);
		//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
		m_msg_id = IdAssigner.preprocessUUID(p_m_msg_id);

		Object[] key = {m_package_id, m_msg_id};
		addInstanceToMap(key);
	}
	static public MessageInCommunication_c createProxy(ModelRoot modelRoot,
			java.util.UUID p_m_package_id, java.util.UUID p_m_msg_id,
			String p_contentPath, IPath p_localPath) {
		ModelRoot resolvedModelRoot = ModelRoot.findModelRoot(modelRoot,
				p_contentPath, p_localPath);
		// if a model root was not resolved it is most likely
		// due to a missing file of the proxy, defualt back to
		// the original model root
		if (resolvedModelRoot != null)
			modelRoot = resolvedModelRoot;
		InstanceList instances = modelRoot
				.getInstanceList(MessageInCommunication_c.class);
		MessageInCommunication_c new_inst = null;
		synchronized (instances) {
			Object[] key = {p_m_package_id, p_m_msg_id};
			new_inst = (MessageInCommunication_c) instances.get(key);
		}
		String contentPath = PersistenceUtil.resolveRelativePath(p_localPath,
				new Path(p_contentPath));
		if (modelRoot.isNewCompareRoot()) {
			// for comparisons we do not want to change
			// the content path
			contentPath = p_contentPath;
		}
		if (new_inst != null && !modelRoot.isCompareRoot()) {
			PersistableModelComponent pmc = new_inst.getPersistableComponent();
			if (pmc == null) {
				// dangling reference, redo this instance
				new_inst.batchUnrelate();
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				new_inst.m_package_id = IdAssigner
						.preprocessUUID(p_m_package_id);
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				new_inst.m_msg_id = IdAssigner.preprocessUUID(p_m_msg_id);

			}
		}
		if (new_inst == null) {
			// there is no instance matching the id, create a proxy
			// if the resource doesn't exist then this will be a dangling reference
			new_inst = new MessageInCommunication_c(modelRoot, p_m_package_id,
					p_m_msg_id);
			new_inst.m_contentPath = contentPath;
		}
		return new_inst;
	}

	static public MessageInCommunication_c resolveInstance(ModelRoot modelRoot,
			java.util.UUID p_m_package_id, java.util.UUID p_m_msg_id) {
		InstanceList instances = modelRoot
				.getInstanceList(MessageInCommunication_c.class);
		MessageInCommunication_c source = null;
		synchronized (instances) {
			Object[] key = {p_m_package_id, p_m_msg_id};
			source = (MessageInCommunication_c) instances.get(key);
			if (source != null && !modelRoot.isCompareRoot()) {
				source.convertFromProxy();
				source.batchUnrelate();
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				source.m_package_id = IdAssigner.preprocessUUID(p_m_package_id);
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				source.m_msg_id = IdAssigner.preprocessUUID(p_m_msg_id);

				return source;
			}
		}
		// there is no instance matching the id
		MessageInCommunication_c new_inst = new MessageInCommunication_c(
				modelRoot, p_m_package_id, p_m_msg_id);
		return new_inst;
	}
	public MessageInCommunication_c(ModelRoot modelRoot) {
		super(modelRoot);
		m_package_id = IdAssigner.NULL_UUID;
		m_msg_id = IdAssigner.NULL_UUID;
		Object[] key = {m_package_id, m_msg_id};
		addInstanceToMap(key);
	}

	public Object getInstanceKey() {
		Object[] key = {m_package_id, m_msg_id};
		return key;
	}

	public boolean setInstanceKey(UUID p_newKey) {

		boolean changed = false;
		// round p1
		// round p2
		// round p3
		// round p4
		// round p5
		if (m_package_id != p_newKey) {

			m_package_id = p_newKey;
			changed = true;
		}
		return changed;
	}

	public boolean equals(Object elem) {
		if (!(elem instanceof MessageInCommunication_c)) {
			return false;
		}
		// check that the model-roots are the same
		if (((NonRootModelElement) elem).getModelRoot() != getModelRoot()) {
			return false;
		}

		return identityEquals(elem);
	}

	public boolean identityEquals(Object elem) {
		if (!(elem instanceof MessageInCommunication_c)) {
			return false;
		}

		MessageInCommunication_c me = (MessageInCommunication_c) elem;
		// don't allow an empty id-value to produce a false positive result;
		// in this case, use whether the two instances are actually the same 
		// one in memory, instead
		if ((IdAssigner.NULL_UUID.equals(getPackage_id()) || IdAssigner.NULL_UUID
				.equals(((MessageInCommunication_c) elem).getPackage_id()))
				&& this != elem) {
			return false;
		}
		if (!getPackage_id().equals(
				((MessageInCommunication_c) elem).getPackage_id()))
			return false;
		// don't allow an empty id-value to produce a false positive result;
		// in this case, use whether the two instances are actually the same 
		// one in memory, instead
		if ((IdAssigner.NULL_UUID.equals(getMsg_id()) || IdAssigner.NULL_UUID
				.equals(((MessageInCommunication_c) elem).getMsg_id()))
				&& this != elem) {
			return false;
		}
		if (!getMsg_id().equals(((MessageInCommunication_c) elem).getMsg_id()))
			return false;
		return true;
	}

	public boolean cachedIdentityEquals(Object elem) {
		if (!(elem instanceof MessageInCommunication_c)) {
			return false;
		}

		MessageInCommunication_c me = (MessageInCommunication_c) elem;
		if (!getPackage_idCachedValue().equals(
				((MessageInCommunication_c) elem).getPackage_idCachedValue()))
			return false;
		if (!getMsg_idCachedValue().equals(
				((MessageInCommunication_c) elem).getMsg_idCachedValue()))
			return false;
		return true;
	}

	// Attributes
	private java.util.UUID m_package_id;
	private java.util.UUID m_msg_id;

	// declare association references from this class

	// referring navigation

	Message_c MayDisplayMessage;
	public void relateAcrossR1135To(Message_c target) {
		relateAcrossR1135To(target, true);
	}
	public void relateAcrossR1135To(Message_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (target == MayDisplayMessage)
			return; // already related

		if (MayDisplayMessage != target) {

			Object oldKey = getInstanceKey();

			if (MayDisplayMessage != null) {

				MayDisplayMessage.clearBackPointerR1135To(this);

				if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) { //$NON-NLS-1$
					Ooaofooa.log
							.println(
									ILogger.CONSISTENCY,
									"MessageInCommunication_c.relateAcrossR1135To(Message_c target)",
									"Relate performed across R1135 from Message in Communication to Message without unrelate of prior instance.");
				}
			}

			MayDisplayMessage = target;
			if (IdAssigner.NULL_UUID.equals(target.getMsg_id())) {
				// do not update cached value
			} else {
				// update cached value
				m_msg_id = target.getMsg_idCachedValue();
			}
			updateInstanceKey(oldKey, getInstanceKey());
			target.setBackPointerR1135To(this);
			target.addRef();
			if (notifyChanges) {
				RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(
						Modeleventnotification_c.DELTA_ELEMENT_RELATED, this,
						target, "1135", "");
				Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(
						change);
			}
		}
	}
	public void unrelateAcrossR1135From(Message_c target) {
		unrelateAcrossR1135From(target, true);
	}
	public void unrelateAcrossR1135From(Message_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (MayDisplayMessage == null)
			return; // already unrelated

		if (target != MayDisplayMessage) {
			Exception e = new Exception();
			e.fillInStackTrace();
			CorePlugin.logError(
					"Tried to unrelate from non-related instance across R1135",
					e);
			return;
		}

		if (target != null) {
			target.clearBackPointerR1135To(this);
		}

		if (MayDisplayMessage != null) {

			m_msg_id = MayDisplayMessage.getMsg_id();
			if (IdAssigner.NULL_UUID.equals(m_msg_id)) {
				m_msg_id = MayDisplayMessage.getMsg_idCachedValue();
			}
			MayDisplayMessage = null;
			target.removeRef();
			if (notifyChanges) {
				RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(
						Modeleventnotification_c.DELTA_ELEMENT_UNRELATED, this,
						target, "1135", "");
				Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(
						change);
			}
		}
	}

	// referring navigation

	Communication_c CanBeDisplayedInCommunication;
	public void relateAcrossR1135To(Communication_c target) {
		relateAcrossR1135To(target, true);
	}
	public void relateAcrossR1135To(Communication_c target,
			boolean notifyChanges) {
		if (target == null)
			return;

		if (target == CanBeDisplayedInCommunication)
			return; // already related

		if (CanBeDisplayedInCommunication != target) {

			Object oldKey = getInstanceKey();

			if (CanBeDisplayedInCommunication != null) {

				CanBeDisplayedInCommunication.clearBackPointerR1135To(this);

				if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) { //$NON-NLS-1$
					Ooaofooa.log
							.println(
									ILogger.CONSISTENCY,
									"MessageInCommunication_c.relateAcrossR1135To(Communication_c target)",
									"Relate performed across R1135 from Message in Communication to Communication without unrelate of prior instance.");
				}
			}

			CanBeDisplayedInCommunication = target;
			if (IdAssigner.NULL_UUID.equals(target.getPackage_id())) {
				// do not update cached value
			} else {
				// update cached value
				m_package_id = target.getPackage_idCachedValue();
			}
			updateInstanceKey(oldKey, getInstanceKey());
			target.setBackPointerR1135To(this);
			target.addRef();
			if (notifyChanges) {
				RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(
						Modeleventnotification_c.DELTA_ELEMENT_RELATED, this,
						target, "1135", "");
				Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(
						change);
			}
		}
	}
	public void unrelateAcrossR1135From(Communication_c target) {
		unrelateAcrossR1135From(target, true);
	}
	public void unrelateAcrossR1135From(Communication_c target,
			boolean notifyChanges) {
		if (target == null)
			return;

		if (CanBeDisplayedInCommunication == null)
			return; // already unrelated

		if (target != CanBeDisplayedInCommunication) {
			Exception e = new Exception();
			e.fillInStackTrace();
			CorePlugin.logError(
					"Tried to unrelate from non-related instance across R1135",
					e);
			return;
		}

		if (target != null) {
			target.clearBackPointerR1135To(this);
		}

		if (CanBeDisplayedInCommunication != null) {

			m_package_id = CanBeDisplayedInCommunication.getPackage_id();
			if (IdAssigner.NULL_UUID.equals(m_package_id)) {
				m_package_id = CanBeDisplayedInCommunication
						.getPackage_idCachedValue();
			}
			CanBeDisplayedInCommunication = null;
			target.removeRef();
			if (notifyChanges) {
				RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(
						Modeleventnotification_c.DELTA_ELEMENT_UNRELATED, this,
						target, "1135", "");
				Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(
						change);
			}
		}
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Message_c[] targets) {
		return getOneCOMM_MICOnR1135(targets, null);
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Message_c[] targets, ClassQueryInterface_c test) {
		MessageInCommunication_c ret_val = null;
		if (targets != null) {
			for (int i = 0; i < targets.length && ret_val == null; ++i) {
				ret_val = getOneCOMM_MICOnR1135(targets[i], test);
			}
		}

		return ret_val;
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Message_c target) {
		return getOneCOMM_MICOnR1135(target, null);
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Message_c target, boolean loadComponent) {
		return getOneCOMM_MICOnR1135(target.getModelRoot(), target, null,
				loadComponent);
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Message_c target, ClassQueryInterface_c test) {
		if (target != null) {
			return getOneCOMM_MICOnR1135(target.getModelRoot(), target, test);
		}
		return null;
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			ModelRoot modelRoot, Message_c target, ClassQueryInterface_c test) {
		return getOneCOMM_MICOnR1135(modelRoot, target, test, true);
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			ModelRoot modelRoot, Message_c target, ClassQueryInterface_c test,
			boolean loadComponent) {
		return find_getOneCOMM_MICOnR1135(modelRoot, target, test);
	}
	private static MessageInCommunication_c find_getOneCOMM_MICOnR1135(
			ModelRoot modelRoot, Message_c target, ClassQueryInterface_c test) {
		if (target != null) {
			synchronized (target.backPointer_CanBeDisplayedInMessageInCommunicationCanBeDisplayedIn_R1135) {
				for (int i = 0; i < target.backPointer_CanBeDisplayedInMessageInCommunicationCanBeDisplayedIn_R1135
						.size(); ++i) {
					MessageInCommunication_c source = (MessageInCommunication_c) target.backPointer_CanBeDisplayedInMessageInCommunicationCanBeDisplayedIn_R1135
							.get(i);
					if (source != null
							&& (test == null || test.evaluate(source))) {
						return source;
					}
				}
			}
		}
		// not found
		return null;
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Message_c[] targets) {
		return getManyCOMM_MICsOnR1135(targets, null);
	}
	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Message_c[] targets, boolean loadComponent) {
		return getManyCOMM_MICsOnR1135(targets, null, loadComponent);
	}
	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Message_c[] targets, ClassQueryInterface_c test) {
		return getManyCOMM_MICsOnR1135(targets, test, true);
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Message_c[] targets, ClassQueryInterface_c test,
			boolean loadComponent) {

		if (targets == null || targets.length == 0 || targets[0] == null)
			return new MessageInCommunication_c[0];

		ModelRoot modelRoot = targets[0].getModelRoot();

		InstanceList instances = modelRoot
				.getInstanceList(MessageInCommunication_c.class);

		Vector matches = new Vector();
		for (int i = 0; i < targets.length; i++) {
			synchronized (targets[i].backPointer_CanBeDisplayedInMessageInCommunicationCanBeDisplayedIn_R1135) {
				for (int j = 0; j < targets[i].backPointer_CanBeDisplayedInMessageInCommunicationCanBeDisplayedIn_R1135
						.size(); ++j) {
					MessageInCommunication_c source = (MessageInCommunication_c) targets[i].backPointer_CanBeDisplayedInMessageInCommunicationCanBeDisplayedIn_R1135
							.get(j);
					if (source != null
							&& (test == null || test.evaluate(source))) {
						matches.add(source);
					}
				}
			}
		}
		if (matches.size() > 0) {
			MessageInCommunication_c[] ret_set = new MessageInCommunication_c[matches
					.size()];
			matches.copyInto(ret_set);
			return ret_set;
		} else {
			return new MessageInCommunication_c[0];
		}
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Message_c target) {
		if (target != null) {
			Message_c[] targetArray = new Message_c[1];
			targetArray[0] = target;
			return getManyCOMM_MICsOnR1135(targetArray);
		} else {
			MessageInCommunication_c[] result = new MessageInCommunication_c[0];
			return result;
		}
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Message_c target, boolean loadComponent) {
		if (target != null) {
			Message_c[] targetArray = new Message_c[1];
			targetArray[0] = target;
			return getManyCOMM_MICsOnR1135(targetArray, loadComponent);
		} else {
			MessageInCommunication_c[] result = new MessageInCommunication_c[0];
			return result;
		}
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Communication_c[] targets) {
		return getOneCOMM_MICOnR1135(targets, null);
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Communication_c[] targets, ClassQueryInterface_c test) {
		MessageInCommunication_c ret_val = null;
		if (targets != null) {
			for (int i = 0; i < targets.length && ret_val == null; ++i) {
				ret_val = getOneCOMM_MICOnR1135(targets[i], test);
			}
		}

		return ret_val;
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Communication_c target) {
		return getOneCOMM_MICOnR1135(target, null);
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Communication_c target, boolean loadComponent) {
		return getOneCOMM_MICOnR1135(target.getModelRoot(), target, null,
				loadComponent);
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			Communication_c target, ClassQueryInterface_c test) {
		if (target != null) {
			return getOneCOMM_MICOnR1135(target.getModelRoot(), target, test);
		}
		return null;
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			ModelRoot modelRoot, Communication_c target,
			ClassQueryInterface_c test) {
		return getOneCOMM_MICOnR1135(modelRoot, target, test, true);
	}

	public static MessageInCommunication_c getOneCOMM_MICOnR1135(
			ModelRoot modelRoot, Communication_c target,
			ClassQueryInterface_c test, boolean loadComponent) {
		return find_getOneCOMM_MICOnR1135(modelRoot, target, test);
	}
	private static MessageInCommunication_c find_getOneCOMM_MICOnR1135(
			ModelRoot modelRoot, Communication_c target,
			ClassQueryInterface_c test) {
		if (target != null) {
			synchronized (target.backPointer_MayDisplayMessageInCommunicationMayDisplay_R1135) {
				for (int i = 0; i < target.backPointer_MayDisplayMessageInCommunicationMayDisplay_R1135
						.size(); ++i) {
					MessageInCommunication_c source = (MessageInCommunication_c) target.backPointer_MayDisplayMessageInCommunicationMayDisplay_R1135
							.get(i);
					if (source != null
							&& (test == null || test.evaluate(source))) {
						return source;
					}
				}
			}
		}
		// not found
		return null;
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Communication_c[] targets) {
		return getManyCOMM_MICsOnR1135(targets, null);
	}
	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Communication_c[] targets, boolean loadComponent) {
		return getManyCOMM_MICsOnR1135(targets, null, loadComponent);
	}
	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Communication_c[] targets, ClassQueryInterface_c test) {
		return getManyCOMM_MICsOnR1135(targets, test, true);
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Communication_c[] targets, ClassQueryInterface_c test,
			boolean loadComponent) {

		if (targets == null || targets.length == 0 || targets[0] == null)
			return new MessageInCommunication_c[0];

		ModelRoot modelRoot = targets[0].getModelRoot();

		InstanceList instances = modelRoot
				.getInstanceList(MessageInCommunication_c.class);

		Vector matches = new Vector();
		for (int i = 0; i < targets.length; i++) {
			synchronized (targets[i].backPointer_MayDisplayMessageInCommunicationMayDisplay_R1135) {
				for (int j = 0; j < targets[i].backPointer_MayDisplayMessageInCommunicationMayDisplay_R1135
						.size(); ++j) {
					MessageInCommunication_c source = (MessageInCommunication_c) targets[i].backPointer_MayDisplayMessageInCommunicationMayDisplay_R1135
							.get(j);
					if (source != null
							&& (test == null || test.evaluate(source))) {
						matches.add(source);
					}
				}
			}
		}
		if (matches.size() > 0) {
			MessageInCommunication_c[] ret_set = new MessageInCommunication_c[matches
					.size()];
			matches.copyInto(ret_set);
			return ret_set;
		} else {
			return new MessageInCommunication_c[0];
		}
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Communication_c target) {
		return getManyCOMM_MICsOnR1135(target, null);
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Communication_c target, boolean loadComponent) {
		return getManyCOMM_MICsOnR1135(target, null, loadComponent);
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Communication_c target, ClassQueryInterface_c test) {
		return getManyCOMM_MICsOnR1135(target, test, true);
	}

	public static MessageInCommunication_c[] getManyCOMM_MICsOnR1135(
			Communication_c target, ClassQueryInterface_c test,
			boolean loadComponent) {
		if (target == null)
			return new MessageInCommunication_c[0];

		ModelRoot modelRoot = target.getModelRoot();
		Vector matches = new Vector();
		synchronized (target.backPointer_MayDisplayMessageInCommunicationMayDisplay_R1135) {
			for (int i = 0; i < target.backPointer_MayDisplayMessageInCommunicationMayDisplay_R1135
					.size(); ++i) {
				MessageInCommunication_c source = (MessageInCommunication_c) target.backPointer_MayDisplayMessageInCommunicationMayDisplay_R1135
						.get(i);
				if (source != null && (test == null || test.evaluate(source))) {

					matches.add(source);
				}
			}
		}

		if (matches.size() > 0) {
			MessageInCommunication_c[] ret_set = new MessageInCommunication_c[matches
					.size()];
			matches.copyInto(ret_set);
			return ret_set;
		} else {
			return new MessageInCommunication_c[0];
		}
	}

	public void batchRelate(ModelRoot modelRoot, boolean notifyChanges,
			boolean searchAllRoots) {
		batchRelate(modelRoot, false, notifyChanges, searchAllRoots);
	}

	public void batchRelate(ModelRoot modelRoot, boolean relateProxies,
			boolean notifyChanges, boolean searchAllRoots) {
		InstanceList instances = null;
		ModelRoot baseRoot = modelRoot;

		// R1135
		Communication_c relInst56001 = (Communication_c) baseRoot
				.getInstanceList(Communication_c.class).get(
						new Object[]{m_package_id});
		// if there was no local element, check for any global elements
		// failing that proceed to check other model roots
		if (relInst56001 == null) {
			relInst56001 = (Communication_c) Ooaofooa.getDefaultInstance()
					.getInstanceList(Communication_c.class)
					.get(new Object[]{m_package_id});
		}
		if (relInst56001 == null && searchAllRoots && !baseRoot.isCompareRoot()) {
			Ooaofooa[] roots = Ooaofooa.getInstances();
			for (int i = 0; i < roots.length; i++) {
				if (roots[i].isCompareRoot()) {
					// never use elements from any compare root
					continue;
				}
				relInst56001 = (Communication_c) roots[i].getInstanceList(
						Communication_c.class).get(new Object[]{m_package_id});
				if (relInst56001 != null)
					break;
			}
		}
		//synchronized
		if (relInst56001 != null) {
			if (relateProxies || !isProxy()
					|| (inSameComponent(this, relInst56001) && !isProxy())) {
				relInst56001.relateAcrossR1135To(this, notifyChanges);
			}
		}

		Message_c relInst56002 = (Message_c) baseRoot.getInstanceList(
				Message_c.class).get(new Object[]{m_msg_id});
		// if there was no local element, check for any global elements
		// failing that proceed to check other model roots
		if (relInst56002 == null) {
			relInst56002 = (Message_c) Ooaofooa.getDefaultInstance()
					.getInstanceList(Message_c.class)
					.get(new Object[]{m_msg_id});
		}
		if (relInst56002 == null && searchAllRoots && !baseRoot.isCompareRoot()) {
			Ooaofooa[] roots = Ooaofooa.getInstances();
			for (int i = 0; i < roots.length; i++) {
				if (roots[i].isCompareRoot()) {
					// never use elements from any compare root
					continue;
				}
				relInst56002 = (Message_c) roots[i].getInstanceList(
						Message_c.class).get(new Object[]{m_msg_id});
				if (relInst56002 != null)
					break;
			}
		}
		//synchronized
		if (relInst56002 != null) {
			if (relateProxies || !isProxy()
					|| (inSameComponent(this, relInst56002) && !isProxy())) {
				relInst56002.relateAcrossR1135To(this, notifyChanges);
			}
		}

	}
	public void batchUnrelate(boolean notifyChanges) {
		NonRootModelElement inst = null;
		// R1135
		// COMM_COMM
		inst = CanBeDisplayedInCommunication;
		unrelateAcrossR1135From(CanBeDisplayedInCommunication, notifyChanges);
		if (inst != null) {
			inst.removeRef();
		}
		// MSG_M
		inst = MayDisplayMessage;
		unrelateAcrossR1135From(MayDisplayMessage, notifyChanges);
		if (inst != null) {
			inst.removeRef();
		}
	}
	public static void batchRelateAll(ModelRoot modelRoot,
			boolean notifyChanges, boolean searchAllRoots) {
		batchRelateAll(modelRoot, notifyChanges, searchAllRoots, false);
	}
	public static void batchRelateAll(ModelRoot modelRoot, boolean notifyChanges, boolean searchAllRoots, boolean relateProxies)
  {
	InstanceList instances = modelRoot.getInstanceList(MessageInCommunication_c.class);
    synchronized(instances) {
        Iterator<NonRootModelElement> cursor = instances.iterator() ;
    	while (cursor.hasNext())
	    {
            final MessageInCommunication_c inst = (MessageInCommunication_c)cursor.next() ;
	        inst.batchRelate(modelRoot, relateProxies, notifyChanges, searchAllRoots );
	    }
	}
  }
	public static void clearInstances(ModelRoot modelRoot) {
		InstanceList instances = modelRoot
				.getInstanceList(MessageInCommunication_c.class);
		synchronized (instances) {
			for (int i = instances.size() - 1; i >= 0; i--) {
				((NonRootModelElement) instances.get(i)).delete_unchecked();
			}

		}
	}

	public static MessageInCommunication_c MessageInCommunicationInstance(
			ModelRoot modelRoot, ClassQueryInterface_c test,
			boolean loadComponent) {
		MessageInCommunication_c result = findMessageInCommunicationInstance(
				modelRoot, test, loadComponent);
		if (result == null && loadComponent) {
			List pmcs = PersistenceManager.findAllComponents(modelRoot,
					MessageInCommunication_c.class);
			for (int i = 0; i < pmcs.size(); i++) {
				PersistableModelComponent component = (PersistableModelComponent) pmcs
						.get(i);
				if (!component.isLoaded()) {
					try {
						component.load(new NullProgressMonitor());
						result = findMessageInCommunicationInstance(modelRoot,
								test, loadComponent);
						if (result != null)
							return result;
					} catch (Exception e) {
						CorePlugin.logError("Error Loading component", e);
					}
				}
			}
		}
		if (result != null && loadComponent) {
			result.loadProxy();
		}
		return result;
	}
	private static MessageInCommunication_c findMessageInCommunicationInstance(
			ModelRoot modelRoot, ClassQueryInterface_c test,
			boolean loadComponent) {
		InstanceList instances = modelRoot
				.getInstanceList(MessageInCommunication_c.class);
		synchronized (instances) {
			for (int i = 0; i < instances.size(); ++i) {
				MessageInCommunication_c x = (MessageInCommunication_c) instances
						.get(i);
				if (test == null || test.evaluate(x)) {
					if (x.ensureLoaded(loadComponent))
						return x;
				}
			}
		}
		return null;
	}
	public static MessageInCommunication_c MessageInCommunicationInstance(
			ModelRoot modelRoot, ClassQueryInterface_c test) {
		return MessageInCommunicationInstance(modelRoot, test, true);
	}

	public static MessageInCommunication_c MessageInCommunicationInstance(
			ModelRoot modelRoot) {
		return MessageInCommunicationInstance(modelRoot, null, true);
	}

	public static MessageInCommunication_c[] MessageInCommunicationInstances(
			ModelRoot modelRoot, ClassQueryInterface_c test,
			boolean loadComponent) {
		if (loadComponent) {
			PersistenceManager.ensureAllInstancesLoaded(modelRoot,
					MessageInCommunication_c.class);
		}
		InstanceList instances = modelRoot
				.getInstanceList(MessageInCommunication_c.class);
		Vector matches = new Vector();
		synchronized (instances) {
			for (int i = 0; i < instances.size(); ++i) {
				MessageInCommunication_c x = (MessageInCommunication_c) instances
						.get(i);
				if (test == null || test.evaluate(x)) {
					if (x.ensureLoaded(loadComponent))
						matches.add(x);
				}
			}
			if (matches.size() > 0) {
				MessageInCommunication_c[] ret_set = new MessageInCommunication_c[matches
						.size()];
				matches.copyInto(ret_set);
				return ret_set;
			} else {
				return new MessageInCommunication_c[0];
			}
		}
	}
	public static MessageInCommunication_c[] MessageInCommunicationInstances(
			ModelRoot modelRoot, ClassQueryInterface_c test) {
		return MessageInCommunicationInstances(modelRoot, test, true);
	}
	public static MessageInCommunication_c[] MessageInCommunicationInstances(
			ModelRoot modelRoot) {
		return MessageInCommunicationInstances(modelRoot, null, true);
	}

	public boolean delete() {
		boolean result = super.delete();
		boolean delete_error = false;
		String errorMsg = "The following relationships were not torn down by the Message in Communication.dispose call: ";
		Communication_c testR1135Inst = Communication_c.getOneCOMM_COMMOnR1135(
				this, false);

		if (testR1135Inst != null) {
			delete_error = true;
			errorMsg = errorMsg + "1135 ";
		}

		Message_c testR1135InstOth = Message_c.getOneMSG_MOnR1135(this, false);

		if (testR1135InstOth != null) {
			delete_error = true;
			errorMsg = errorMsg + "1135 ";
		}
		if (delete_error == true) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log.println(ILogger.DELETE,
						"Message in Communication", errorMsg);
			} else {
				Exception e = new Exception();
				e.fillInStackTrace();
				CorePlugin.logError(errorMsg, e);
			}
		}
		return result;
	}

	// end declare instance pool

	// declare attribute accessors
	public boolean isUUID(String attributeName) {
		if (attributeName.equals("package_id")) {
			return true;
		}
		if (attributeName.equals("msg_id")) {
			return true;
		}
		return false;
	}
	public String getCompUniqueID() {
		UUID tempID = null;
		long longID = 0L;
		StringBuffer result = new StringBuffer();

		tempID = getPackage_id();

		if (IdAssigner.NULL_UUID.equals(tempID))
			tempID = getPackage_idCachedValue();
		result.append(Long.toHexString(tempID.getMostSignificantBits()));
		result.append(Long.toHexString(tempID.getLeastSignificantBits()));
		tempID = getMsg_id();

		if (IdAssigner.NULL_UUID.equals(tempID))
			tempID = getMsg_idCachedValue();
		result.append(Long.toHexString(tempID.getMostSignificantBits()));
		result.append(Long.toHexString(tempID.getLeastSignificantBits()));
		return result.toString();
	}
	// declare attribute accessors
	public long getPackage_idLongBased() {
		if (CanBeDisplayedInCommunication != null) {
			return CanBeDisplayedInCommunication.getPackage_idLongBased();
		}
		return 0;
	}
	public java.util.UUID getPackage_id() {
		if (CanBeDisplayedInCommunication != null) {
			return CanBeDisplayedInCommunication.getPackage_id();
		}
		return IdAssigner.NULL_UUID;
	}

	public java.util.UUID getPackage_idCachedValue() {
		if (!IdAssigner.NULL_UUID.equals(m_package_id))
			return m_package_id;
		else
			return getPackage_id();
	}

	public void setPackage_id(java.util.UUID newValue) {
		if (newValue != null) {
			if (newValue.equals(m_package_id)) {
				return;
			}
		} else if (m_package_id != null) {
			if (m_package_id.equals(newValue)) {
				return;
			}
		} else {
			return;
		}
		AttributeChangeModelDelta change = new AttributeChangeModelDelta(
				Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this,
				"Package_id", m_package_id, newValue, true);
		m_package_id = IdAssigner.preprocessUUID(newValue);
		Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
	}
	public long getMsg_idLongBased() {
		if (MayDisplayMessage != null) {
			return MayDisplayMessage.getMsg_idLongBased();
		}
		return 0;
	}
	public java.util.UUID getMsg_id() {
		if (MayDisplayMessage != null) {
			return MayDisplayMessage.getMsg_id();
		}
		return IdAssigner.NULL_UUID;
	}

	public java.util.UUID getMsg_idCachedValue() {
		if (!IdAssigner.NULL_UUID.equals(m_msg_id))
			return m_msg_id;
		else
			return getMsg_id();
	}

	public void setMsg_id(java.util.UUID newValue) {
		if (newValue != null) {
			if (newValue.equals(m_msg_id)) {
				return;
			}
		} else if (m_msg_id != null) {
			if (m_msg_id.equals(newValue)) {
				return;
			}
		} else {
			return;
		}
		AttributeChangeModelDelta change = new AttributeChangeModelDelta(
				Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this,
				"Msg_id", m_msg_id, newValue, true);
		m_msg_id = IdAssigner.preprocessUUID(newValue);
		Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
	}
	// end declare accessors
	public static void checkClassConsistency(ModelRoot modelRoot) {
		Ooaofooa.log
				.println(ILogger.OPERATION, "Message in Communication", //$NON-NLS-1$
						" Operation entered: Message in Communication::checkClassConsistency"); //$NON-NLS-1$
		if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) { //$NON-NLS-1$
			return;
		}
		MessageInCommunication_c[] objs = MessageInCommunication_c
				.MessageInCommunicationInstances(modelRoot, null, false);

		for (int i = 0; i < objs.length; i++) {
			objs[i].checkConsistency();
		}
	}
	public boolean checkConsistency() {
		Ooaofooa.log
				.println(ILogger.OPERATION, "Message in Communication", //$NON-NLS-1$
						" Operation entered: Message in Communication::checkConsistency"); //$NON-NLS-1$
		if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) { //$NON-NLS-1$
			return true;
		}
		ModelRoot modelRoot = getModelRoot();
		boolean retval = true;
		class MessageInCommunication_c_test56004_c
				implements
					ClassQueryInterface_c {
			MessageInCommunication_c_test56004_c(java.util.UUID p56005,
					java.util.UUID p56006) {
				m_p56005 = p56005;
				m_p56006 = p56006;
			}
			private java.util.UUID m_p56005;
			private java.util.UUID m_p56006;
			public boolean evaluate(Object candidate) {
				MessageInCommunication_c selected = (MessageInCommunication_c) candidate;
				boolean retval = false;
				retval = (selected.getPackage_id().equals(m_p56005))
						& (selected.getMsg_id().equals(m_p56006));
				return retval;
			}
		}

		MessageInCommunication_c[] objs56003 = MessageInCommunication_c
				.MessageInCommunicationInstances(modelRoot,
						new MessageInCommunication_c_test56004_c(
								getPackage_id(), getMsg_id()));

		if (((objs56003.length) == 0)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(
								ILogger.CONSISTENCY,
								"Message in Communication", //$NON-NLS-1$
								"Consistency: Object: Message in Communication: Cardinality of an identifier is zero. " //$NON-NLS-1$
										+ "Actual Value: " + Integer.toString(objs56003.length)); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: Message in Communication: Cardinality of an identifier is zero. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs56003.length), e);
			}
			retval = false;

		}

		if (((objs56003.length) > 1)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(
								ILogger.CONSISTENCY,
								"Message in Communication", //$NON-NLS-1$
								"Consistency: Object: Message in Communication: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$
										+ "Actual Value: " //$NON-NLS-1$ 
										+ Integer.toString(objs56003.length)
										+ " Package_ID: " + "Not Printable" + " Msg_ID: " + "Not Printable"); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: Message in Communication: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs56003.length)
										+ " Package_ID: " + "Not Printable" + " Msg_ID: " + "Not Printable", e); //$NON-NLS-1$
			}
			retval = false;

		}

		// Message in Communication is a link class in association: rel.Numb = 1135
		// The one side class in the association is: Communication
		class Communication_c_test56010_c implements ClassQueryInterface_c {
			Communication_c_test56010_c(java.util.UUID p56011) {
				m_p56011 = p56011;
			}
			private java.util.UUID m_p56011;
			public boolean evaluate(Object candidate) {
				Communication_c selected = (Communication_c) candidate;
				boolean retval = false;
				retval = (selected.getPackage_id().equals(m_p56011));
				return retval;
			}
		}

		Communication_c[] objs56009 = Communication_c.CommunicationInstances(
				modelRoot, new Communication_c_test56010_c(getPackage_id()));

		if (((objs56009.length) > 1)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(
								ILogger.CONSISTENCY,
								"Message in Communication", //$NON-NLS-1$
								"Consistency: Object: Message in Communication: Association: 1135: Cardinality of one side of link is greater than 1. " //$NON-NLS-1$
										+ "Actual Value: " + Integer.toString(objs56009.length)); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: Message in Communication: Association: 1135: Cardinality of one side of link is greater than 1. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs56009.length), e);
			}
			retval = false;

		}

		// Other side
		return retval;
	}

	public Object getAdapter(Class adapter) {
		Object superAdapter = super.getAdapter(adapter);
		if (superAdapter != null) {
			return superAdapter;
		}
		return null;
	}
} // end Message in Communication
