      
package com.mentor.nucleus.bp.core ;
//====================================================================
//
// File:      com.mentor.nucleus.bp.core.ProvidedOperation_c.java
//
// WARNING: Do not edit this generated file
// Generated by ../MC-Java/java.arc, $Revision: 1.111 $
//
// (c) Copyright 2005-2014 by Mentor Graphics Corp.  All rights reserved.
//
//====================================================================

// No special imports
import java.util.* ;
import java.lang.reflect.*;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.runtime.IAdaptable;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import com.mentor.nucleus.bp.core.util.PersistenceUtil;
import org.eclipse.core.runtime.NullProgressMonitor;
import com.mentor.nucleus.bp.core.ui.marker.UmlProblem;
import com.mentor.nucleus.bp.core.common.*;      
abstract class EV_PROVIDED_OPERATION extends genericEvent_c 
{
  public abstract int getEvtcode() ;
}

public class ProvidedOperation_c extends NonRootModelElement implements IAdaptable, Cloneable
{
  // Public Constructors
  public ProvidedOperation_c(ModelRoot modelRoot,
       java.util.UUID         p_m_id,
       String       p_m_name,
       String       p_m_descrip,
       String       p_m_action_semantics_internal,
       int  p_m_suc_pars)
  {
    super(modelRoot);
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       m_id = IdAssigner.preprocessUUID(p_m_id);
       m_name = p_m_name;
       m_descrip = p_m_descrip;
       // default value for m_action_semantics
       m_action_semantics_internal = p_m_action_semantics_internal;
       m_suc_pars = p_m_suc_pars;
        
    Object [] key = {m_id};
    addInstanceToMap(key);
  }
  static public ProvidedOperation_c createProxy(ModelRoot modelRoot,
       java.util.UUID         p_m_id,
       String       p_m_name,
       String       p_m_descrip,
       String       p_m_action_semantics_internal,
       int  p_m_suc_pars, String p_contentPath, IPath p_localPath)
  {
	  ModelRoot resolvedModelRoot = ModelRoot.findModelRoot(modelRoot, p_contentPath, p_localPath);
	  // if a model root was not resolved it is most likely
	  // due to a missing file of the proxy, defualt back to
	  // the original model root
	  if(resolvedModelRoot != null)
	  	modelRoot = resolvedModelRoot;
      InstanceList instances = modelRoot.getInstanceList(ProvidedOperation_c.class);
      ProvidedOperation_c new_inst = null;
      synchronized(instances) {
          Object[] key = {p_m_id};
          new_inst = (ProvidedOperation_c) instances.get(key) ;
        }
	String contentPath = PersistenceUtil.resolveRelativePath(
			p_localPath,
			new Path(p_contentPath));
	if(modelRoot.isNewCompareRoot()) {
	      // for comparisons we do not want to change
	      // the content path
	      contentPath = p_contentPath;
	}
	if ( new_inst != null && !modelRoot.isCompareRoot()) {
		PersistableModelComponent pmc = new_inst.getPersistableComponent();
		if (pmc == null) {
			// dangling reference, redo this instance
			new_inst.batchUnrelate();
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       new_inst.m_id = IdAssigner.preprocessUUID(p_m_id);
       new_inst.m_name = p_m_name;
       new_inst.m_descrip = p_m_descrip;
       // default value for m_action_semantics
       new_inst.m_action_semantics_internal = p_m_action_semantics_internal;
       new_inst.m_suc_pars = p_m_suc_pars;
        
		}
	}
	if ( new_inst == null ) {
		// there is no instance matching the id, create a proxy
		// if the resource doesn't exist then this will be a dangling reference
    	new_inst = new ProvidedOperation_c(modelRoot,
p_m_id,
p_m_name,
p_m_descrip,
p_m_action_semantics_internal,
p_m_suc_pars
);
		new_inst.m_contentPath = contentPath;
	}
    return new_inst;
  }

  static public ProvidedOperation_c resolveInstance(ModelRoot modelRoot,
       java.util.UUID         p_m_id,
       String       p_m_name,
       String       p_m_descrip,
       String       p_m_action_semantics_internal,
       int  p_m_suc_pars){
    InstanceList instances = modelRoot.getInstanceList(ProvidedOperation_c.class);
    ProvidedOperation_c source = null;
    synchronized(instances) {
        Object [] key = {
        p_m_id
            };
        source = (ProvidedOperation_c) instances.get(key);
        if (source != null && !modelRoot.isCompareRoot()) {
           source.convertFromProxy();
           source.batchUnrelate();
       //pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
       source.m_id = IdAssigner.preprocessUUID(p_m_id);
       source.m_name = p_m_name;
       source.m_descrip = p_m_descrip;
       // default value for m_action_semantics
       source.m_action_semantics_internal = p_m_action_semantics_internal;
       source.m_suc_pars = p_m_suc_pars;
        
           return source ;
        }
      }
      // there is no instance matching the id
    ProvidedOperation_c new_inst = new ProvidedOperation_c(modelRoot,
p_m_id,
p_m_name,
p_m_descrip,
p_m_action_semantics_internal,
p_m_suc_pars
);
    return new_inst;
  }
  public ProvidedOperation_c(ModelRoot modelRoot)
  {
    super(modelRoot);
     m_id = IdAssigner.NULL_UUID;   
     m_name = "";   
     m_descrip = "";   
     m_action_semantics = "";   
     m_action_semantics_internal = "";   
     m_suc_pars = Parsestatus_c.OOA_UNINITIALIZED_ENUM;
    Object [] key = {m_id};
    addInstanceToMap(key);
  }

  public Object getInstanceKey() {
    Object [] key =  {m_id};
		return key;
  }
  
  public boolean setInstanceKey(UUID p_newKey){
  
  	boolean changed = false;
		// round p1
		// round p2
		// round p3
			// round p4
			// round p5
	if (m_id !=  p_newKey ){
	
		m_id = p_newKey; 	
		changed = true;
	}
  	return changed;
  }
  

  



  public boolean equals (Object elem) {
     if (!(elem instanceof ProvidedOperation_c)) {
         return false;
     }
	    // check that the model-roots are the same
    	if (((NonRootModelElement)elem).getModelRoot() != getModelRoot()) {
    		return false;
    	}
    	
     return identityEquals(elem);
  }
  
   public boolean identityEquals(Object elem) {
       if (!(elem instanceof ProvidedOperation_c)) {
           return false;
       }
       
       ProvidedOperation_c me = (ProvidedOperation_c)elem;
      // don't allow an empty id-value to produce a false positive result;
      // in this case, use whether the two instances are actually the same 
      // one in memory, instead
      if ((IdAssigner.NULL_UUID.equals(getId()) || IdAssigner.NULL_UUID.equals(((ProvidedOperation_c)elem).getId())) && this != elem) {
      	return false;
      }
      if (!getId().equals(((ProvidedOperation_c)elem).getId())) return false;
      return true;
    }

   public boolean cachedIdentityEquals(Object elem) {
       if (!(elem instanceof ProvidedOperation_c)) {
           return false;
       }
       
       ProvidedOperation_c me = (ProvidedOperation_c)elem;
      if (!getIdCachedValue().equals(((ProvidedOperation_c)elem).getIdCachedValue())) return false;
      return true;
    }


  // Attributes
  private java.util.UUID         m_id ;
  private String       m_name ;
  private String       m_descrip ;
  private String       m_action_semantics ;
  private String       m_action_semantics_internal ;
  private int  m_suc_pars ;
      
// declare association references from this class
  
  
    
// referring navigation

ProvidedExecutableProperty_c IsSupertypeProvidedExecutableProperty ;
public void relateAcrossR4503To(ProvidedExecutableProperty_c target)
{
	relateAcrossR4503To(target, true);
}
public void relateAcrossR4503To(ProvidedExecutableProperty_c target, boolean notifyChanges)
{
	if (target == null) return;
	
	if (target == IsSupertypeProvidedExecutableProperty) return;  // already related

    if ( IsSupertypeProvidedExecutableProperty != target ) {
    
    Object oldKey = getInstanceKey();

    if (IsSupertypeProvidedExecutableProperty != null) {
    
        IsSupertypeProvidedExecutableProperty.clearBackPointerR4503To(this);
        
		if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) {   //$NON-NLS-1$
		Ooaofooa.log.println(ILogger.CONSISTENCY, 
			"ProvidedOperation_c.relateAcrossR4503To(ProvidedExecutableProperty_c target)", 
			"Relate performed across R4503 from Provided Operation to Provided Executable Property without unrelate of prior instance.");  
		}
    }
                
    	IsSupertypeProvidedExecutableProperty = target ;
        m_id = target.getId();
      updateInstanceKey(oldKey, getInstanceKey());
	    target.setBackPointerR4503To(this);
        target.addRef();
      if(notifyChanges) {
	    	RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(Modeleventnotification_c.DELTA_ELEMENT_RELATED, this, target, "4503", "");
        Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(change);
      }
    }
}
public void unrelateAcrossR4503From(ProvidedExecutableProperty_c target)
{
	unrelateAcrossR4503From(target, true);
}
public void unrelateAcrossR4503From(ProvidedExecutableProperty_c target, boolean notifyChanges)
{
	if (target == null) return;
	
	if (IsSupertypeProvidedExecutableProperty == null) return;  // already unrelated
	
	if (target != IsSupertypeProvidedExecutableProperty) {
		Exception e = new Exception();
		e.fillInStackTrace();
		CorePlugin.logError("Tried to unrelate from non-related instance across R4503", e);
		return;
	}

    if (target != null) {
        target.clearBackPointerR4503To(this);
    }
    

      if(IsSupertypeProvidedExecutableProperty != null) {
      
        m_id = IsSupertypeProvidedExecutableProperty.getId();
        IsSupertypeProvidedExecutableProperty = null ;
        target.removeRef();
      if(notifyChanges) { 
        RelationshipChangeModelDelta change = new RelationshipChangeModelDelta(Modeleventnotification_c.DELTA_ELEMENT_UNRELATED, this, target, "4503", "");
        Ooaofooa.getDefaultInstance().fireModelElementRelationChanged(change);
      }
    }
}

  
    
      
public static ProvidedOperation_c getOneSPR_POOnR4503(ProvidedExecutableProperty_c [] targets)
{
    return getOneSPR_POOnR4503(targets, null);
}

public static ProvidedOperation_c getOneSPR_POOnR4503(ProvidedExecutableProperty_c [] targets, ClassQueryInterface_c test)
{
    ProvidedOperation_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           ret_val = getOneSPR_POOnR4503(targets[i], test);
        }
    }

    return ret_val;
}

public static ProvidedOperation_c getOneSPR_POOnR4503(ProvidedExecutableProperty_c target)
{
  return getOneSPR_POOnR4503(target, null);
}

public static ProvidedOperation_c getOneSPR_POOnR4503(ProvidedExecutableProperty_c target, boolean loadComponent)
{
    return getOneSPR_POOnR4503(target.getModelRoot(), target, null, loadComponent);
}

public static ProvidedOperation_c getOneSPR_POOnR4503(ProvidedExecutableProperty_c target, ClassQueryInterface_c test)
{
  if (target != null) {
    return getOneSPR_POOnR4503(target.getModelRoot(), target, test);
  }
  return null;
}

public static ProvidedOperation_c getOneSPR_POOnR4503(ModelRoot modelRoot, ProvidedExecutableProperty_c target, ClassQueryInterface_c test)
{
	return getOneSPR_POOnR4503(modelRoot, target, test, true);
}

public static ProvidedOperation_c getOneSPR_POOnR4503(ModelRoot modelRoot, ProvidedExecutableProperty_c target, ClassQueryInterface_c test, boolean loadComponent)
{
   return find_getOneSPR_POOnR4503(modelRoot,target,test);
}
private static ProvidedOperation_c find_getOneSPR_POOnR4503(ModelRoot modelRoot, ProvidedExecutableProperty_c target, ClassQueryInterface_c test)
{
  if (target != null) {
    ProvidedOperation_c source = (ProvidedOperation_c)target.backPointer_IsSubtypeProvidedOperationIsSubtype_R4503;
    if (source != null && (test == null || test.evaluate(source))) {
      return source;
    }
  }
  // not found
  return null ;
}

public static ProvidedOperation_c [] getManySPR_POsOnR4503(ProvidedExecutableProperty_c [] targets)
{
  return getManySPR_POsOnR4503(targets, null);
}
public static ProvidedOperation_c [] getManySPR_POsOnR4503(ProvidedExecutableProperty_c [] targets, boolean loadComponent)
{
  return getManySPR_POsOnR4503(targets, null, loadComponent);
}
public static ProvidedOperation_c [] getManySPR_POsOnR4503(ProvidedExecutableProperty_c [] targets, ClassQueryInterface_c test)
{
	return getManySPR_POsOnR4503(targets, test, true);
}

public static ProvidedOperation_c [] getManySPR_POsOnR4503(ProvidedExecutableProperty_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{

  if(targets == null || targets.length == 0 || targets[0] == null)
  	return new ProvidedOperation_c[0];

  ModelRoot modelRoot = targets[0].getModelRoot();
 
   InstanceList instances = modelRoot.getInstanceList(ProvidedOperation_c.class);

  Vector matches = new Vector();
  for (int i = 0 ; i < targets.length ; i++) {
      ProvidedOperation_c source = (ProvidedOperation_c)targets[i].backPointer_IsSubtypeProvidedOperationIsSubtype_R4503;
      if (source != null && (test == null || test.evaluate(source))) {
        matches.add(source);
      }
  }
  if (matches.size() > 0) {
	ProvidedOperation_c[] ret_set = new ProvidedOperation_c[matches.size()];
	matches.copyInto(ret_set);
	return ret_set;
  } else {
	return new ProvidedOperation_c[0];
  }
  }

public static ProvidedOperation_c [] getManySPR_POsOnR4503(ProvidedExecutableProperty_c target)
{
  if (target != null) {
    ProvidedExecutableProperty_c [] targetArray = new ProvidedExecutableProperty_c[1];
    targetArray[0] = target;
    return getManySPR_POsOnR4503(targetArray);
  } else {
    ProvidedOperation_c [] result = new ProvidedOperation_c [0] ;
  return result ;
}
}

public static ProvidedOperation_c [] getManySPR_POsOnR4503(ProvidedExecutableProperty_c target, boolean loadComponent)
{
  if (target != null) {
    ProvidedExecutableProperty_c [] targetArray = new ProvidedExecutableProperty_c[1];
    targetArray[0] = target;
    return getManySPR_POsOnR4503(targetArray, loadComponent);
  } else {
    ProvidedOperation_c [] result = new ProvidedOperation_c [0] ;
  return result ;
}
}




// declare associations referring to this class

    
  
  
// referred to navigation

ArrayList<InterfaceOperationInvocation_c> backPointer_InterfaceOperationInvocation_R680 = new ArrayList<InterfaceOperationInvocation_c>();

public void setInterfaceOperationInvocationOrderInChildListR680(InterfaceOperationInvocation_c target, int index) {
	unrelateAcrossR680From(target);
	InterfaceOperationInvocation_c[] elements = InterfaceOperationInvocation_c.getManyACT_IOPsOnR680(this);
	int count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			unrelateAcrossR680From((InterfaceOperationInvocation_c) elements[i]); 
		}
		count++;
	}
	relateAcrossR680To(target);
	count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			relateAcrossR680To((InterfaceOperationInvocation_c) elements[i]);
		}
		count++;
	}
}

public void relateAcrossR680To(InterfaceOperationInvocation_c target)
{
  if (target != null) {
    target.relateAcrossR680To(this, true) ;
  }
}

public void relateAcrossR680To(InterfaceOperationInvocation_c target, boolean notifyChanges)
{
  if (target != null) {
    target.relateAcrossR680To(this, notifyChanges) ;
  }
}

public void setBackPointerR680To(InterfaceOperationInvocation_c target)
{
  	synchronized (backPointer_InterfaceOperationInvocation_R680) {
		backPointer_InterfaceOperationInvocation_R680.add(target);
	}
}

public void unrelateAcrossR680From(InterfaceOperationInvocation_c target)
{
  if (target != null) {
    target.unrelateAcrossR680From(this, true) ;
  }
}

public void unrelateAcrossR680From(InterfaceOperationInvocation_c target, boolean notifyChanges)
{
  if (target != null) {
    target.unrelateAcrossR680From(this, notifyChanges) ;
  }
}

public void clearBackPointerR680To(InterfaceOperationInvocation_c target)
{
  synchronized (backPointer_InterfaceOperationInvocation_R680) {
	    backPointer_InterfaceOperationInvocation_R680.remove(target);
	}
}

public static ProvidedOperation_c getOneSPR_POOnR680(InterfaceOperationInvocation_c [] targets)
{
    return getOneSPR_POOnR680(targets, null);
}

public static ProvidedOperation_c getOneSPR_POOnR680(InterfaceOperationInvocation_c [] targets, ClassQueryInterface_c test)
{
    return getOneSPR_POOnR680(targets, test, true);
}

public static ProvidedOperation_c getOneSPR_POOnR680(InterfaceOperationInvocation_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{
    ProvidedOperation_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           if (test != null) {
             ProvidedOperation_c candidate_val = getOneSPR_POOnR680(targets[i],true);
             if ( candidate_val != null && test.evaluate(candidate_val) )
             {
               ret_val = candidate_val;
               break;
             }
           }
           else {
             ret_val = getOneSPR_POOnR680(targets[i], loadComponent);
             if (ret_val != null) {
               break;
             }
           }
        }
    }
    return ret_val;
}

public static ProvidedOperation_c getOneSPR_POOnR680(InterfaceOperationInvocation_c target)
{
	return getOneSPR_POOnR680(target, true);
}
public static ProvidedOperation_c getOneSPR_POOnR680(InterfaceOperationInvocation_c target, boolean loadComponent)
{
  if (target != null) {
    return target.IsInvocationOfProvidedOperation ;
  } else {
    return null;
  }
}

public static ProvidedOperation_c [] getManySPR_POsOnR680(InterfaceOperationInvocation_c [] targets,
    ClassQueryInterface_c test)
{
	return getManySPR_POsOnR680(targets, test, true);
}

public static ProvidedOperation_c [] getManySPR_POsOnR680(InterfaceOperationInvocation_c [] targets,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if(targets == null || targets.length == 0 || targets[0] == null)
    return new ProvidedOperation_c[0];
  
  
  LinkedHashSet<ProvidedOperation_c> elementsSet = new LinkedHashSet<ProvidedOperation_c>();
  for (int i = 0; i < targets.length; i++) {
    ProvidedOperation_c associate = targets[i].IsInvocationOfProvidedOperation;
    if (targets[i] != null && associate != null
    	&& (test == null || test.evaluate(associate))) {
        	if (elementsSet.add(associate)){ 
            }
    }
  }

  ProvidedOperation_c[] result = new ProvidedOperation_c[elementsSet.size()];
  elementsSet.toArray(result);
  return result;
}

public static ProvidedOperation_c [] getManySPR_POsOnR680(InterfaceOperationInvocation_c [] targets)
{
  return getManySPR_POsOnR680(targets, null);
}

public static ProvidedOperation_c [] getManySPR_POsOnR680(InterfaceOperationInvocation_c target,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if (target != null) {
    InterfaceOperationInvocation_c [] targetArray = new InterfaceOperationInvocation_c[1];
    targetArray[0] = target;
    return getManySPR_POsOnR680(targetArray, test, loadComponent);
  } else {
    ProvidedOperation_c [] result = new ProvidedOperation_c [0] ;
    return result ;
  }
  
}

public static ProvidedOperation_c [] getManySPR_POsOnR680(InterfaceOperationInvocation_c target,
    ClassQueryInterface_c test)
{
    return getManySPR_POsOnR680(target, null, true);
}

public static ProvidedOperation_c [] getManySPR_POsOnR680(InterfaceOperationInvocation_c target)
{
    return getManySPR_POsOnR680(target, null, true);
}

public static ProvidedOperation_c [] getManySPR_POsOnR680(InterfaceOperationInvocation_c target, boolean loadComponent)
{
    return getManySPR_POsOnR680(target, null, loadComponent);
}


    
  
  
// referred to navigation

ProvidedOperationBody_c backPointer_ProvidedOperationBody_R687;

public void setProvidedOperationBodyOrderInChildListR687(ProvidedOperationBody_c target, int index) {
	unrelateAcrossR687From(target);
	ProvidedOperationBody_c[] elements = ProvidedOperationBody_c.getManyACT_POBsOnR687(this);
	int count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			unrelateAcrossR687From((ProvidedOperationBody_c) elements[i]); 
		}
		count++;
	}
	relateAcrossR687To(target);
	count = 0;
	for(int i = 0; i < elements.length; i++) {
		if(count >= index) {
			relateAcrossR687To((ProvidedOperationBody_c) elements[i]);
		}
		count++;
	}
}

public void relateAcrossR687To(ProvidedOperationBody_c target)
{
  if (target != null) {
    target.relateAcrossR687To(this, true) ;
  }
}

public void relateAcrossR687To(ProvidedOperationBody_c target, boolean notifyChanges)
{
  if (target != null) {
    target.relateAcrossR687To(this, notifyChanges) ;
  }
}

public void setBackPointerR687To(ProvidedOperationBody_c target)
{
    backPointer_ProvidedOperationBody_R687 = target;
}

public void unrelateAcrossR687From(ProvidedOperationBody_c target)
{
  if (target != null) {
    target.unrelateAcrossR687From(this, true) ;
  }
}

public void unrelateAcrossR687From(ProvidedOperationBody_c target, boolean notifyChanges)
{
  if (target != null) {
    target.unrelateAcrossR687From(this, notifyChanges) ;
  }
}

public void clearBackPointerR687To(ProvidedOperationBody_c target)
{
	if (target == backPointer_ProvidedOperationBody_R687) {
		backPointer_ProvidedOperationBody_R687 = null;
	}
}

public static ProvidedOperation_c getOneSPR_POOnR687(ProvidedOperationBody_c [] targets)
{
    return getOneSPR_POOnR687(targets, null);
}

public static ProvidedOperation_c getOneSPR_POOnR687(ProvidedOperationBody_c [] targets, ClassQueryInterface_c test)
{
    return getOneSPR_POOnR687(targets, test, true);
}

public static ProvidedOperation_c getOneSPR_POOnR687(ProvidedOperationBody_c [] targets, ClassQueryInterface_c test, boolean loadComponent)
{
    ProvidedOperation_c ret_val = null;
    if (targets != null)
    {
        for (int i = 0; i < targets.length && ret_val == null; ++i )
        {
           if (test != null) {
             ProvidedOperation_c candidate_val = getOneSPR_POOnR687(targets[i],true);
             if ( candidate_val != null && test.evaluate(candidate_val) )
             {
               ret_val = candidate_val;
               break;
             }
           }
           else {
             ret_val = getOneSPR_POOnR687(targets[i], loadComponent);
             if (ret_val != null) {
               break;
             }
           }
        }
    }
    return ret_val;
}

public static ProvidedOperation_c getOneSPR_POOnR687(ProvidedOperationBody_c target)
{
	return getOneSPR_POOnR687(target, true);
}
public static ProvidedOperation_c getOneSPR_POOnR687(ProvidedOperationBody_c target, boolean loadComponent)
{
  if (target != null) {
    return target.SpecifiesProcessingForProvidedOperation ;
  } else {
    return null;
  }
}

public static ProvidedOperation_c [] getManySPR_POsOnR687(ProvidedOperationBody_c [] targets,
    ClassQueryInterface_c test)
{
	return getManySPR_POsOnR687(targets, test, true);
}

public static ProvidedOperation_c [] getManySPR_POsOnR687(ProvidedOperationBody_c [] targets,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if(targets == null || targets.length == 0 || targets[0] == null)
    return new ProvidedOperation_c[0];
  
  
  LinkedHashSet<ProvidedOperation_c> elementsSet = new LinkedHashSet<ProvidedOperation_c>();
  for (int i = 0; i < targets.length; i++) {
    ProvidedOperation_c associate = targets[i].SpecifiesProcessingForProvidedOperation;
    if (targets[i] != null && associate != null
    	&& (test == null || test.evaluate(associate))) {
        	if (elementsSet.add(associate)){ 
            }
    }
  }

  ProvidedOperation_c[] result = new ProvidedOperation_c[elementsSet.size()];
  elementsSet.toArray(result);
  return result;
}

public static ProvidedOperation_c [] getManySPR_POsOnR687(ProvidedOperationBody_c [] targets)
{
  return getManySPR_POsOnR687(targets, null);
}

public static ProvidedOperation_c [] getManySPR_POsOnR687(ProvidedOperationBody_c target,
    ClassQueryInterface_c test, boolean loadComponent)
{
  if (target != null) {
    ProvidedOperationBody_c [] targetArray = new ProvidedOperationBody_c[1];
    targetArray[0] = target;
    return getManySPR_POsOnR687(targetArray, test, loadComponent);
  } else {
    ProvidedOperation_c [] result = new ProvidedOperation_c [0] ;
    return result ;
  }
  
}

public static ProvidedOperation_c [] getManySPR_POsOnR687(ProvidedOperationBody_c target,
    ClassQueryInterface_c test)
{
    return getManySPR_POsOnR687(target, null, true);
}

public static ProvidedOperation_c [] getManySPR_POsOnR687(ProvidedOperationBody_c target)
{
    return getManySPR_POsOnR687(target, null, true);
}

public static ProvidedOperation_c [] getManySPR_POsOnR687(ProvidedOperationBody_c target, boolean loadComponent)
{
    return getManySPR_POsOnR687(target, null, loadComponent);
}


      
  public void batchRelate(ModelRoot modelRoot, boolean notifyChanges, boolean searchAllRoots)
  {
      batchRelate(modelRoot, false, notifyChanges, searchAllRoots);
  }
  
  public void batchRelate(ModelRoot modelRoot, boolean relateProxies, boolean notifyChanges, boolean searchAllRoots)
  {
        InstanceList instances=null;
        ModelRoot baseRoot = modelRoot;

      // R4503
      ProvidedExecutableProperty_c relInst55602 = (ProvidedExecutableProperty_c) baseRoot.getInstanceList(ProvidedExecutableProperty_c.class).get(new Object[] {m_id});
            // if there was no local element, check for any global elements
            // failing that proceed to check other model roots
      		if (relInst55602 == null) {
      			relInst55602 = (ProvidedExecutableProperty_c) Ooaofooa.getDefaultInstance().getInstanceList(ProvidedExecutableProperty_c.class).get(new Object[] {m_id});
      		}
			if (relInst55602 == null && searchAllRoots && !baseRoot.isCompareRoot()) {
				Ooaofooa[] roots = Ooaofooa.getInstances();
				for (int i = 0; i < roots.length; i++) {
				    if(roots[i].isCompareRoot()) {
				         // never use elements from any compare root
				         continue;
				    }
					relInst55602 = (ProvidedExecutableProperty_c) roots[i].getInstanceList(ProvidedExecutableProperty_c.class).get(new Object[] {m_id});
					if (relInst55602 != null)
						break;
				}
			}
			//synchronized
      if ( relInst55602 != null )
      {
          if (relateProxies || !isProxy() || (inSameComponent(this, relInst55602) && !isProxy())) {
	      relInst55602.relateAcrossR4503To(this, notifyChanges);
	  }
	  }
	          
	}
  public void batchUnrelate(boolean notifyChanges)
  {
		NonRootModelElement inst=null;
      // R4503
      // SPR_PEP
		  inst=IsSupertypeProvidedExecutableProperty;
			unrelateAcrossR4503From(IsSupertypeProvidedExecutableProperty, notifyChanges);
          if ( inst != null ) {
			   inst.removeRef();
	      }
	}
  public static void batchRelateAll(ModelRoot modelRoot, boolean notifyChanges, boolean searchAllRoots) {
		batchRelateAll(modelRoot, notifyChanges, searchAllRoots, false);
  }	  
  public static void batchRelateAll(ModelRoot modelRoot, boolean notifyChanges, boolean searchAllRoots, boolean relateProxies)
  {
	InstanceList instances = modelRoot.getInstanceList(ProvidedOperation_c.class);
    synchronized(instances) {
        Iterator<NonRootModelElement> cursor = instances.iterator() ;
    	while (cursor.hasNext())
	    {
            final ProvidedOperation_c inst = (ProvidedOperation_c)cursor.next() ;
	        inst.batchRelate(modelRoot, relateProxies, notifyChanges, searchAllRoots );
	    }
	}
  }

  public static void clearInstances(ModelRoot modelRoot)
  {
    InstanceList instances = modelRoot.getInstanceList(ProvidedOperation_c.class);
    synchronized(instances) {
       for(int i=instances.size()-1; i>=0; i--){
              ((NonRootModelElement)instances.get(i)).delete_unchecked();
       }
    
    }
  }

  public static ProvidedOperation_c ProvidedOperationInstance(ModelRoot modelRoot, ClassQueryInterface_c test, boolean loadComponent)
  {
  		ProvidedOperation_c result=findProvidedOperationInstance(modelRoot,test,loadComponent);
  		if(result==null && loadComponent){
     List pmcs =  PersistenceManager.findAllComponents(modelRoot,ProvidedOperation_c.class);
		for (int i = 0; i < pmcs.size(); i++) {
			PersistableModelComponent component = (PersistableModelComponent) pmcs
				.get(i);
			if (!component.isLoaded()) {
				try {
					component.load(new NullProgressMonitor());
					 result=findProvidedOperationInstance(modelRoot,test,loadComponent);
					 if(result!=null) return result;
				} catch (Exception e) {
					CorePlugin.logError("Error Loading component", e);
				}
			}
		}
	    }
	    if(result!=null && loadComponent){
    	    result.loadProxy();
	    }
	  return result;  
  }
private static ProvidedOperation_c findProvidedOperationInstance(ModelRoot modelRoot, ClassQueryInterface_c test, boolean loadComponent)
{
	InstanceList instances = modelRoot.getInstanceList(ProvidedOperation_c.class);
		synchronized (instances) {
            for (int i = 0; i < instances.size(); ++i) {
				ProvidedOperation_c x = (ProvidedOperation_c) instances.get(i);
				if (test==null || test.evaluate(x)){
					if(x.ensureLoaded(loadComponent))
					return x;
			}
		}
		}
			return null;
}
  public static ProvidedOperation_c ProvidedOperationInstance(ModelRoot modelRoot, ClassQueryInterface_c test){
     return ProvidedOperationInstance(modelRoot,test,true);
  }
  
  public static ProvidedOperation_c ProvidedOperationInstance(ModelRoot modelRoot)
  {
	 return ProvidedOperationInstance(modelRoot,null,true);
  }

  public static ProvidedOperation_c [] ProvidedOperationInstances(ModelRoot modelRoot, ClassQueryInterface_c test, boolean loadComponent)
  {	
            if(loadComponent){
  			   PersistenceManager.ensureAllInstancesLoaded(modelRoot, ProvidedOperation_c.class);
  			}
		    InstanceList instances = modelRoot.getInstanceList(ProvidedOperation_c.class);
			Vector matches = new Vector();
			synchronized (instances) {
                for (int i = 0; i < instances.size(); ++i) {
					ProvidedOperation_c x = (ProvidedOperation_c) instances.get(i);
					if (test==null ||test.evaluate(x)){
						if(x.ensureLoaded(loadComponent))
						matches.add(x);
			    }
				}
			if (matches.size() > 0) {
				ProvidedOperation_c[] ret_set = new ProvidedOperation_c[matches.size()];
				matches.copyInto(ret_set);
				return ret_set;
			} else {
				return new ProvidedOperation_c[0];
			}		
		} 
  }
  public static ProvidedOperation_c [] ProvidedOperationInstances(ModelRoot modelRoot, ClassQueryInterface_c test){
    return  ProvidedOperationInstances(modelRoot,test,true);
  }
  public static ProvidedOperation_c [] ProvidedOperationInstances(ModelRoot modelRoot)
  {
	return ProvidedOperationInstances(modelRoot,null,true);
  }

  public boolean delete()
  {
    boolean result = super.delete();
	boolean delete_error = false;
	String errorMsg = "The following relationships were not torn down by the Provided Operation.dispose call: ";
	ProvidedExecutableProperty_c testR4503Inst2 = ProvidedExecutableProperty_c.getOneSPR_PEPOnR4503(this, false);

	if ( testR4503Inst2 != null )
	{
	delete_error = true;	        
	errorMsg = errorMsg + "4503 ";
	}
	InterfaceOperationInvocation_c testR680Inst = InterfaceOperationInvocation_c.getOneACT_IOPOnR680(this, false);

	if ( testR680Inst != null )
	{
	delete_error = true;
	errorMsg = errorMsg + "680 ";	
	}
	ProvidedOperationBody_c testR687Inst = ProvidedOperationBody_c.getOneACT_POBOnR687(this, false);

	if ( testR687Inst != null )
	{
	delete_error = true;
	errorMsg = errorMsg + "687 ";	
	}
	if(delete_error == true) {

		if(CorePlugin.getDefault().isDebugging()) {
			Ooaofooa.log.println(ILogger.DELETE, "Provided Operation", errorMsg);
		}
		else {
			Exception e = new Exception();
            e.fillInStackTrace();
			CorePlugin.logError(errorMsg, e);
		}
	}
	return result;
  }

  // end declare instance pool

  // declare attribute accessors
  public boolean isUUID(String attributeName){
      if(attributeName.equals("id")){
         return true;
      }
      return false;      
  }      
 public String getCompUniqueID(){
    UUID tempID=null;
    long longID=0L;
    StringBuffer result= new StringBuffer();
    
    tempID= getId();
    
        if(IdAssigner.NULL_UUID.equals(tempID))
	      tempID=getIdCachedValue(); 
	      result.append(Long.toHexString(tempID.getMostSignificantBits()));
          result.append(Long.toHexString(tempID.getLeastSignificantBits()));
    return result.toString();
 }
  // declare attribute accessors
  public long getIdLongBased()
  {
    if ( IsSupertypeProvidedExecutableProperty != null )
    {
      return IsSupertypeProvidedExecutableProperty.getIdLongBased();
    }
    return 0;  
  }          
  public java.util.UUID getId()
  {
    if ( IsSupertypeProvidedExecutableProperty != null )
    {
      return IsSupertypeProvidedExecutableProperty.getId();
    }
    return IdAssigner.NULL_UUID;
  }

 public boolean hasSuperType(){
 	return  ( IsSupertypeProvidedExecutableProperty != null );
 
 }                  

  public java.util.UUID getIdCachedValue()
  {
    if ( !IdAssigner.NULL_UUID.equals(m_id) )
      return m_id;
    else
      return getId();
  }
  
  public void setId(java.util.UUID newValue)
  {
	if(newValue != null){
	    if(newValue.equals(m_id)){
	        return;
	    }
	}else if(m_id != null){
	    if(m_id.equals(newValue)){
	        return;
	    }
	}else{
	    return;
	}
	AttributeChangeModelDelta change = new AttributeChangeModelDelta(Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this, "Id", m_id, newValue,true); 
   m_id = IdAssigner.preprocessUUID(newValue);
    Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
  }
  public String getName()
  {
ModelRoot modelRoot = getModelRoot();
ExecutableProperty_c v_ep = ExecutableProperty_c.getOneC_EPOnR4501(ProvidedExecutableProperty_c.getOneSPR_PEPOnR4503(this));


InterfaceOperation_c v_operation = InterfaceOperation_c.getOneC_IOOnR4004(v_ep);


if ( (  (v_operation != null)) )
{

Setcachedname(			    
v_ep.getName() ) ;


return v_ep.getName();



}

else
{

if ( (  (v_ep != null)) )
{

return v_ep.Getcachedname();



}

else
{

return Getcachedname();



}


}


  }


  public String getDescrip()
  {
ModelRoot modelRoot = getModelRoot();
ExecutableProperty_c v_ep = ExecutableProperty_c.getOneC_EPOnR4501(ProvidedExecutableProperty_c.getOneSPR_PEPOnR4503(this));


InterfaceOperation_c v_operation = InterfaceOperation_c.getOneC_IOOnR4004(v_ep);


if ( (  (v_operation != null)) )
{

Setcacheddescrip(			    
v_ep.getDescrip() ) ;


return v_operation.getDescrip();



}

else
{

if ( (  (v_ep != null)) )
{

return v_ep.Getcacheddescrip();



}

else
{

return Getcacheddescrip();



}


}


  }


  public String getAction_semantics()
  {
ModelRoot modelRoot = getModelRoot();
return Ooaofooa.Convertrelocatabletags(modelRoot			    
,getAction_semantics_internal());



  }


  public String getAction_semantics_internal()
  {
    return m_action_semantics_internal ;
  }


  public void setAction_semantics_internal(String newValue)
  {
	if(newValue != null){
	    if(newValue.equals(m_action_semantics_internal)){
	        return;
	    }
	}else if(m_action_semantics_internal != null){
	    if(m_action_semantics_internal.equals(newValue)){
	        return;
	    }
	}else{
	    return;
	}
	AttributeChangeModelDelta change = new AttributeChangeModelDelta(Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this, "Action_semantics_internal", m_action_semantics_internal, newValue,true); 
   m_action_semantics_internal = newValue ;
    Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
  }
  public int getSuc_pars()
  {
    return m_suc_pars ;
  }


  public void setSuc_pars(int newValue)
  {
    if(m_suc_pars == newValue){
        return;
    }
    AttributeChangeModelDelta change = new AttributeChangeModelDelta(Modeleventnotification_c.DELTA_ATTRIBUTE_CHANGE, this, "Suc_pars", new Integer(m_suc_pars), new Integer(newValue),true);

   m_suc_pars = newValue ;
    Ooaofooa.getDefaultInstance().fireModelElementAttributeChanged(change);
  }
  // end declare accessors
  public static void checkClassConsistency (ModelRoot modelRoot) {
    Ooaofooa.log.println(
	  ILogger.OPERATION,
	  "Provided Operation", //$NON-NLS-1$
	  " Operation entered: Provided Operation::checkClassConsistency"); //$NON-NLS-1$
     if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) {  //$NON-NLS-1$
       return;
     }
     ProvidedOperation_c [] objs = ProvidedOperation_c.ProvidedOperationInstances(modelRoot,null,false); 
     
     for ( int i = 0; i < objs.length; i++) {
       objs[i].checkConsistency();
     }  
  } 
  public boolean checkConsistency () {
    Ooaofooa.log.println(
	  ILogger.OPERATION,
	  "Provided Operation", //$NON-NLS-1$
	  " Operation entered: Provided Operation::checkConsistency");  //$NON-NLS-1$
    if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) {  //$NON-NLS-1$
      return true;
    }
	ModelRoot modelRoot = getModelRoot();
    boolean      retval = true;
    class ProvidedOperation_c_test55604_c implements ClassQueryInterface_c
    {
	  ProvidedOperation_c_test55604_c( java.util.UUID            p55605 ) {
	  m_p55605 = p55605;
	  }
	  private java.util.UUID             m_p55605; 
	  public boolean evaluate (Object candidate)
	  {
	      ProvidedOperation_c selected = (ProvidedOperation_c) candidate;
	      boolean retval = false;
	      retval = (selected.getId().equals(m_p55605));
	      return retval;
	  }
    }

    ProvidedOperation_c [] objs55603 = 
    ProvidedOperation_c.ProvidedOperationInstances(modelRoot, new ProvidedOperation_c_test55604_c(getId())) ;

    if ( (  (objs55603.length) == 0) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Provided Operation", //$NON-NLS-1$
           "Consistency: Object: Provided Operation: Cardinality of an identifier is zero. " //$NON-NLS-1$
           + "Actual Value: " + Integer.toString( objs55603.length ) ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Provided Operation: Cardinality of an identifier is zero. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs55603.length )  , e); 
      }
      retval = false;

    }

    if ( (  (objs55603.length) > 1) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Provided Operation", //$NON-NLS-1$
           "Consistency: Object: Provided Operation: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$
           + "Actual Value: " //$NON-NLS-1$ 
           + Integer.toString( objs55603.length )  + " Id: " + "Not Printable" ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Provided Operation: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs55603.length )  + " Id: " + "Not Printable" , e); //$NON-NLS-1$
      }
      retval = false;

    }

          // Provided Operation is a subtype in association: rel.Numb = 4503
          // The supertype class is: Provided Executable Property
    class ProvidedExecutableProperty_c_test55609_c implements ClassQueryInterface_c
    {
	  ProvidedExecutableProperty_c_test55609_c( java.util.UUID            p55610 ) {
	  m_p55610 = p55610;
	  }
	  private java.util.UUID             m_p55610; 
	  public boolean evaluate (Object candidate)
	  {
	      ProvidedExecutableProperty_c selected = (ProvidedExecutableProperty_c) candidate;
	      boolean retval = false;
	      retval = (selected.getId().equals(m_p55610));
	      return retval;
	  }
    }

    ProvidedExecutableProperty_c [] objs55608 = 
    ProvidedExecutableProperty_c.ProvidedExecutablePropertyInstances(modelRoot, new ProvidedExecutableProperty_c_test55609_c(getId())) ;

    if ( (  (objs55608.length) != 1) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Provided Operation", //$NON-NLS-1$
           "Consistency: Object: Provided Operation: Association: 4503: Cardinality of a supertype is not equal to 1. " //$NON-NLS-1$
           + "Actual Value: " + Integer.toString( objs55608.length ) ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Provided Operation: Association: 4503: Cardinality of a supertype is not equal to 1. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs55608.length )  , e); 
      }
      retval = false;

    }

          // Provided Operation is a participating class in association: rel.Numb = 680
             // Object: Interface Operation Invocation
          // Provided Operation is a participating class in association: rel.Numb = 687
             // Object: Provided Operation Body
    class ProvidedOperationBody_c_test55612_c implements ClassQueryInterface_c
    {
	  ProvidedOperationBody_c_test55612_c( java.util.UUID            p55613 ) {
	  m_p55613 = p55613;
	  }
	  private java.util.UUID             m_p55613; 
	  public boolean evaluate (Object candidate)
	  {
	      ProvidedOperationBody_c selected = (ProvidedOperationBody_c) candidate;
	      boolean retval = false;
	      retval = (selected.getId().equals(m_p55613));
	      return retval;
	  }
    }

    ProvidedOperationBody_c [] objs55611 = 
    ProvidedOperationBody_c.ProvidedOperationBodyInstances(modelRoot, new ProvidedOperationBody_c_test55612_c(getId())) ;

    if ( (  (objs55611.length) > 1) )
    {

      if (CorePlugin.getDefault().isDebugging()){
          Ooaofooa.log.println(ILogger.CONSISTENCY, "Provided Operation", //$NON-NLS-1$
           "Consistency: Object: Provided Operation: Association: 687: Cardinality of a formalizer is greater than 1. " //$NON-NLS-1$
           + "Actual Value: " + Integer.toString( objs55611.length ) ); //$NON-NLS-1$
      }
      else {
          Exception e = new Exception();
          CorePlugin.logError("Consistency: Object: Provided Operation: Association: 687: Cardinality of a formalizer is greater than 1. " //$NON-NLS-1$ 
          + "Actual Value: " //$NON-NLS-1$
          + Integer.toString( objs55611.length )  , e); 
      }
      retval = false;

    }

    return retval;
  }


  // declare transform functions
  public  void Initialize()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Initialize") ; 
               final ModelRoot modelRoot = getModelRoot();
setSuc_pars( Parsestatus_c.parseInitial) ;



   } // End initialize
  public  void Dispose()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Dispose") ; 
               final ModelRoot modelRoot = getModelRoot();
ProvidedExecutableProperty_c v_pep = ProvidedExecutableProperty_c.getOneSPR_PEPOnR4503(this);


if ( (  (v_pep != null)) )
{

this.unrelateAcrossR4503From(v_pep);


if (v_pep != null) {
v_pep.Dispose() ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}

ProvidedOperationBody_c v_pro_body = ProvidedOperationBody_c.getOneACT_POBOnR687(this);


if ( (  (v_pro_body != null)) )
{

this.unrelateAcrossR687From(v_pro_body);


if (v_pro_body != null) {
v_pro_body.Dispose() ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}

InterfaceOperationInvocation_c [] v_invocations = InterfaceOperationInvocation_c.getManyACT_IOPsOnR680(this);


InterfaceOperationInvocation_c  v_iop = null;
for ( int i53796 = 0; i53796 < v_invocations.length; i53796++)
{
  v_iop = v_invocations[i53796] ;

this.unrelateAcrossR680From(v_iop);



}

if ( delete() ) {
    Ooaofooa.getDefaultInstance().fireModelElementDeleted(new BaseModelDelta(Modeleventnotification_c.DELTA_DELETE, this));
}



   } // End dispose
  public  java.util.UUID         Getcomponentid()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Getcomponentid") ; 
               final ModelRoot modelRoot = getModelRoot();
ProvidedExecutableProperty_c v_pep = ProvidedExecutableProperty_c.getOneSPR_PEPOnR4503(this);


return v_pep.Getcomponentid();



   } // End getComponentId
  public  int          Getmessagedirection()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Getmessagedirection") ; 
               final ModelRoot modelRoot = getModelRoot();
InterfaceOperation_c v_operation = InterfaceOperation_c.getOneC_IOOnR4004(ExecutableProperty_c.getOneC_EPOnR4501(ProvidedExecutableProperty_c.getOneSPR_PEPOnR4503(this)));


if ( (  (v_operation != null)) )
{

if ( (v_operation.getDirection() == Ifdirectiontype_c.ClientServer) )
{

return 0;



}

else if ( (v_operation.getDirection() == Ifdirectiontype_c.ServerClient) )
{

return 1;



}

else
{

return 2;



}


}

else
{

return -1;



}


   } // End getMessageDirection
  public  boolean      Issynchronized()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Issynchronized") ; 
               final ModelRoot modelRoot = getModelRoot();
ProvidedExecutableProperty_c v_pep = ProvidedExecutableProperty_c.getOneSPR_PEPOnR4503(this);


if ( (  (v_pep != null)) )
{

return v_pep.Issynchronized();



}

return true;



   } // End isSynchronized
  public  Object Converttoinstance()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Converttoinstance") ; 
return this;
   } // End convertToInstance
  public  void Collectchanges(final Object p_Changelist)
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Collectchanges") ; 
               final ModelRoot modelRoot = getModelRoot();
if ( (  !Issynchronized()) )
{

Util_c.Createelementchange(			    
"removed"			    
,p_Changelist			    
,Converttoinstance()			    
,true ) ;



}


   } // End collectChanges
  public  void Synchronize()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Synchronize") ; 
               final ModelRoot modelRoot = getModelRoot();
if ( (  !Issynchronized()) )
{

Provision_c v_provision = Provision_c.getOneC_POnR4501(ProvidedExecutableProperty_c.getOneSPR_PEPOnR4503(this));


if ( (  (v_provision != null)) )
{

if (v_provision != null) {
v_provision.Synchronize() ;
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Attempted to call an operation on a null instance.", t);
}



}


}


   } // End synchronize
  public  String       Getcachedname()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Getcachedname") ; 
	return m_name;
   } // End getCachedName
  public  void Setcachedname(final String       p_Name)
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Setcachedname") ; 
	m_name = p_Name;
   } // End setCachedName
  public  void Initializeunparsed()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Initializeunparsed") ; 
               final ModelRoot modelRoot = getModelRoot();
ProvidedOperationBody_c v_pob = ProvidedOperationBody_c.getOneACT_POBOnR687(this);


if (   (v_pob == null) )
{

v_pob = new ProvidedOperationBody_c(modelRoot) ;


  this.relateAcrossR687To(v_pob);



}

Body_c v_bdy = Body_c.getOneACT_ACTOnR698(v_pob);


if (   (v_bdy == null) )
{

v_bdy = new Body_c(modelRoot) ;


if (v_bdy != null) {
  v_bdy.relateAcrossR698To(v_pob);
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Relate attempted on null left hand instance.", t);
}



}

Block_c v_blk = Block_c.getOneACT_BLKOnR650(v_bdy);


if (   (v_blk == null) )
{

v_blk = new Block_c(modelRoot) ;


if (v_bdy != null) {
  v_bdy.relateAcrossR650To(v_blk);
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Relate attempted on null left hand instance.", t);
}


if (v_bdy != null) {
  v_bdy.relateAcrossR612To(v_blk);
}
else {
  Throwable t = new Throwable();
  t.fillInStackTrace();
  CorePlugin.logError("Relate attempted on null left hand instance.", t);
}



}


   } // End initializeUnparsed
  public  String       Getcacheddescrip()
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Getcacheddescrip") ; 
	return m_descrip;
   } // End getCachedDescrip
  public  void Setcacheddescrip(final String       p_Descrip)
  {
      Ooaofooa.log.println(ILogger.OPERATION, "Provided Operation", " Operation entered: ProvidedOperation::Setcacheddescrip") ; 
	m_descrip = p_Descrip;
   } // End setCachedDescrip

  // end transform functions


  public Object getAdapter(Class adapter) {
    Object superAdapter = super.getAdapter(adapter);
    if(superAdapter != null) {
    	return superAdapter;
    }
	  return null;
  }
} // end Provided Operation
