package com.mentor.nucleus.bp.core;
//====================================================================
//
// File:      com.mentor.nucleus.bp.core.WhileStmt_c.java
//
// WARNING: Do not edit this generated file
// Generated by ../MC-Java/java.arc, $Revision: 1.111 $
//
// (c) Copyright 2005-2014 by Mentor Graphics Corp.  All rights reserved.
//
//====================================================================

// No special imports
import java.util.*;
import java.lang.reflect.*;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.runtime.IAdaptable;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import com.mentor.nucleus.bp.core.util.PersistenceUtil;
import org.eclipse.core.runtime.NullProgressMonitor;
import com.mentor.nucleus.bp.core.ui.marker.UmlProblem;
import com.mentor.nucleus.bp.core.common.*;
abstract class EV_WHILE_STMT extends genericEvent_c {
	public abstract int getEvtcode();
}

public class WhileStmt_c extends NonRootModelElement
		implements
			IAdaptable,
			Cloneable {
	// Public Constructors
	public WhileStmt_c(ModelRoot modelRoot, java.util.UUID p_m_statement_id,
			java.util.UUID p_m_value_id, java.util.UUID p_m_block_id) {
		super(modelRoot);
		//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
		m_statement_id = IdAssigner.preprocessUUID(p_m_statement_id);
		//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
		m_value_id = IdAssigner.preprocessUUID(p_m_value_id);
		//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
		m_block_id = IdAssigner.preprocessUUID(p_m_block_id);

		Object[] key = {m_statement_id};
		addInstanceToMap(key);
	}
	static public WhileStmt_c createProxy(ModelRoot modelRoot,
			java.util.UUID p_m_statement_id, java.util.UUID p_m_value_id,
			java.util.UUID p_m_block_id, String p_contentPath, IPath p_localPath) {
		ModelRoot resolvedModelRoot = ModelRoot.findModelRoot(modelRoot,
				p_contentPath, p_localPath);
		// if a model root was not resolved it is most likely
		// due to a missing file of the proxy, defualt back to
		// the original model root
		if (resolvedModelRoot != null)
			modelRoot = resolvedModelRoot;
		InstanceList instances = modelRoot.getInstanceList(WhileStmt_c.class);
		WhileStmt_c new_inst = null;
		synchronized (instances) {
			Object[] key = {p_m_statement_id};
			new_inst = (WhileStmt_c) instances.get(key);
		}
		String contentPath = PersistenceUtil.resolveRelativePath(p_localPath,
				new Path(p_contentPath));
		if (modelRoot.isNewCompareRoot()) {
			// for comparisons we do not want to change
			// the content path
			contentPath = p_contentPath;
		}
		if (new_inst != null && !modelRoot.isCompareRoot()) {
			PersistableModelComponent pmc = new_inst.getPersistableComponent();
			if (pmc == null) {
				// dangling reference, redo this instance
				new_inst.batchUnrelate();
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				new_inst.m_statement_id = IdAssigner
						.preprocessUUID(p_m_statement_id);
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				new_inst.m_value_id = IdAssigner.preprocessUUID(p_m_value_id);
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				new_inst.m_block_id = IdAssigner.preprocessUUID(p_m_block_id);

			}
		}
		if (new_inst == null) {
			// there is no instance matching the id, create a proxy
			// if the resource doesn't exist then this will be a dangling reference
			new_inst = new WhileStmt_c(modelRoot, p_m_statement_id,
					p_m_value_id, p_m_block_id);
			new_inst.m_contentPath = contentPath;
		}
		return new_inst;
	}

	static public WhileStmt_c resolveInstance(ModelRoot modelRoot,
			java.util.UUID p_m_statement_id, java.util.UUID p_m_value_id,
			java.util.UUID p_m_block_id) {
		InstanceList instances = modelRoot.getInstanceList(WhileStmt_c.class);
		WhileStmt_c source = null;
		synchronized (instances) {
			Object[] key = {p_m_statement_id};
			source = (WhileStmt_c) instances.get(key);
			if (source != null && !modelRoot.isCompareRoot()) {
				source.convertFromProxy();
				source.batchUnrelate();
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				source.m_statement_id = IdAssigner
						.preprocessUUID(p_m_statement_id);
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				source.m_value_id = IdAssigner.preprocessUUID(p_m_value_id);
				//pre-process the uuid so that we re-use null uuid instance rather then creating a new one.           
				source.m_block_id = IdAssigner.preprocessUUID(p_m_block_id);

				return source;
			}
		}
		// there is no instance matching the id
		WhileStmt_c new_inst = new WhileStmt_c(modelRoot, p_m_statement_id,
				p_m_value_id, p_m_block_id);
		return new_inst;
	}
	public WhileStmt_c(ModelRoot modelRoot) {
		super(modelRoot);
		m_statement_id = IdAssigner.NULL_UUID;
		m_value_id = IdAssigner.NULL_UUID;
		m_block_id = IdAssigner.NULL_UUID;
		Object[] key = {m_statement_id};
		addInstanceToMap(key);
	}

	public Object getInstanceKey() {
		Object[] key = {m_statement_id};
		return key;
	}

	public boolean setInstanceKey(UUID p_newKey) {

		boolean changed = false;
		// round p1
		// round p2
		// round p3
		// round p4
		// round p5
		if (m_statement_id != p_newKey) {

			m_statement_id = p_newKey;
			changed = true;
		}
		return changed;
	}

	public boolean equals(Object elem) {
		if (!(elem instanceof WhileStmt_c)) {
			return false;
		}
		// check that the model-roots are the same
		if (((NonRootModelElement) elem).getModelRoot() != getModelRoot()) {
			return false;
		}

		return identityEquals(elem);
	}

	public boolean identityEquals(Object elem) {
		if (!(elem instanceof WhileStmt_c)) {
			return false;
		}

		WhileStmt_c me = (WhileStmt_c) elem;
		// don't allow an empty id-value to produce a false positive result;
		// in this case, use whether the two instances are actually the same 
		// one in memory, instead
		if ((IdAssigner.NULL_UUID.equals(getStatement_id()) || IdAssigner.NULL_UUID
				.equals(((WhileStmt_c) elem).getStatement_id()))
				&& this != elem) {
			return false;
		}
		if (!getStatement_id().equals(((WhileStmt_c) elem).getStatement_id()))
			return false;
		return true;
	}

	public boolean cachedIdentityEquals(Object elem) {
		if (!(elem instanceof WhileStmt_c)) {
			return false;
		}

		WhileStmt_c me = (WhileStmt_c) elem;
		if (!getStatement_idCachedValue().equals(
				((WhileStmt_c) elem).getStatement_idCachedValue()))
			return false;
		return true;
	}

	// Attributes
	private java.util.UUID m_statement_id;
	private java.util.UUID m_value_id;
	private java.util.UUID m_block_id;

	// declare association references from this class

	// referring navigation

	Statement_c IsSupertypeStatement;
	public void relateAcrossR603To(Statement_c target) {
		relateAcrossR603To(target, true);
	}
	public void relateAcrossR603To(Statement_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (target == IsSupertypeStatement)
			return; // already related

		if (IsSupertypeStatement != target) {

			Object oldKey = getInstanceKey();

			if (IsSupertypeStatement != null) {

				IsSupertypeStatement.clearBackPointerR603To(this);

				if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) { //$NON-NLS-1$
					Ooaofooa.log
							.println(
									ILogger.CONSISTENCY,
									"WhileStmt_c.relateAcrossR603To(Statement_c target)",
									"Relate performed across R603 from While Stmt to Statement without unrelate of prior instance.");
				}
			}

			IsSupertypeStatement = target;
			m_statement_id = target.getStatement_id();
			updateInstanceKey(oldKey, getInstanceKey());
			target.setBackPointerR603To(this);
			target.addRef();
		}
	}
	public void unrelateAcrossR603From(Statement_c target) {
		unrelateAcrossR603From(target, true);
	}
	public void unrelateAcrossR603From(Statement_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (IsSupertypeStatement == null)
			return; // already unrelated

		if (target != IsSupertypeStatement) {
			Exception e = new Exception();
			e.fillInStackTrace();
			CorePlugin.logError(
					"Tried to unrelate from non-related instance across R603",
					e);
			return;
		}

		if (target != null) {
			target.clearBackPointerR603To(this);
		}

		if (IsSupertypeStatement != null) {

			m_statement_id = IsSupertypeStatement.getStatement_id();
			IsSupertypeStatement = null;
			target.removeRef();
		}
	}

	public static WhileStmt_c getOneACT_WHLOnR603(Statement_c[] targets) {
		return getOneACT_WHLOnR603(targets, null);
	}

	public static WhileStmt_c getOneACT_WHLOnR603(Statement_c[] targets,
			ClassQueryInterface_c test) {
		WhileStmt_c ret_val = null;
		if (targets != null) {
			for (int i = 0; i < targets.length && ret_val == null; ++i) {
				ret_val = getOneACT_WHLOnR603(targets[i], test);
			}
		}

		return ret_val;
	}

	public static WhileStmt_c getOneACT_WHLOnR603(Statement_c target) {
		return getOneACT_WHLOnR603(target, null);
	}

	public static WhileStmt_c getOneACT_WHLOnR603(Statement_c target,
			boolean loadComponent) {
		return getOneACT_WHLOnR603(target.getModelRoot(), target, null,
				loadComponent);
	}

	public static WhileStmt_c getOneACT_WHLOnR603(Statement_c target,
			ClassQueryInterface_c test) {
		if (target != null) {
			return getOneACT_WHLOnR603(target.getModelRoot(), target, test);
		}
		return null;
	}

	public static WhileStmt_c getOneACT_WHLOnR603(ModelRoot modelRoot,
			Statement_c target, ClassQueryInterface_c test) {
		return getOneACT_WHLOnR603(modelRoot, target, test, true);
	}

	public static WhileStmt_c getOneACT_WHLOnR603(ModelRoot modelRoot,
			Statement_c target, ClassQueryInterface_c test,
			boolean loadComponent) {
		return find_getOneACT_WHLOnR603(modelRoot, target, test);
	}
	private static WhileStmt_c find_getOneACT_WHLOnR603(ModelRoot modelRoot,
			Statement_c target, ClassQueryInterface_c test) {
		if (target != null) {
			WhileStmt_c source = (WhileStmt_c) target.backPointer_IsSubtypeWhileStmtIsSubtype_R603;
			if (source != null && (test == null || test.evaluate(source))) {
				return source;
			}
		}
		// not found
		return null;
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR603(Statement_c[] targets) {
		return getManyACT_WHLsOnR603(targets, null);
	}
	public static WhileStmt_c[] getManyACT_WHLsOnR603(Statement_c[] targets,
			boolean loadComponent) {
		return getManyACT_WHLsOnR603(targets, null, loadComponent);
	}
	public static WhileStmt_c[] getManyACT_WHLsOnR603(Statement_c[] targets,
			ClassQueryInterface_c test) {
		return getManyACT_WHLsOnR603(targets, test, true);
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR603(Statement_c[] targets,
			ClassQueryInterface_c test, boolean loadComponent) {

		if (targets == null || targets.length == 0 || targets[0] == null)
			return new WhileStmt_c[0];

		ModelRoot modelRoot = targets[0].getModelRoot();

		InstanceList instances = modelRoot.getInstanceList(WhileStmt_c.class);

		Vector matches = new Vector();
		for (int i = 0; i < targets.length; i++) {
			WhileStmt_c source = (WhileStmt_c) targets[i].backPointer_IsSubtypeWhileStmtIsSubtype_R603;
			if (source != null && (test == null || test.evaluate(source))) {
				matches.add(source);
			}
		}
		if (matches.size() > 0) {
			WhileStmt_c[] ret_set = new WhileStmt_c[matches.size()];
			matches.copyInto(ret_set);
			return ret_set;
		} else {
			return new WhileStmt_c[0];
		}
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR603(Statement_c target) {
		if (target != null) {
			Statement_c[] targetArray = new Statement_c[1];
			targetArray[0] = target;
			return getManyACT_WHLsOnR603(targetArray);
		} else {
			WhileStmt_c[] result = new WhileStmt_c[0];
			return result;
		}
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR603(Statement_c target,
			boolean loadComponent) {
		if (target != null) {
			Statement_c[] targetArray = new Statement_c[1];
			targetArray[0] = target;
			return getManyACT_WHLsOnR603(targetArray, loadComponent);
		} else {
			WhileStmt_c[] result = new WhileStmt_c[0];
			return result;
		}
	}

	// referring navigation

	Block_c ControlsBlock;
	public void relateAcrossR608To(Block_c target) {
		relateAcrossR608To(target, true);
	}
	public void relateAcrossR608To(Block_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (target == ControlsBlock)
			return; // already related

		if (ControlsBlock != target) {

			Object oldKey = getInstanceKey();

			if (ControlsBlock != null) {

				ControlsBlock.clearBackPointerR608To(this);

				if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) { //$NON-NLS-1$
					Ooaofooa.log
							.println(
									ILogger.CONSISTENCY,
									"WhileStmt_c.relateAcrossR608To(Block_c target)",
									"Relate performed across R608 from While Stmt to Block without unrelate of prior instance.");
				}
			}

			ControlsBlock = target;
			m_block_id = target.getBlock_id();
			updateInstanceKey(oldKey, getInstanceKey());
			target.setBackPointerR608To(this);
			target.addRef();
		}
	}
	public void unrelateAcrossR608From(Block_c target) {
		unrelateAcrossR608From(target, true);
	}
	public void unrelateAcrossR608From(Block_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (ControlsBlock == null)
			return; // already unrelated

		if (target != ControlsBlock) {
			Exception e = new Exception();
			e.fillInStackTrace();
			CorePlugin.logError(
					"Tried to unrelate from non-related instance across R608",
					e);
			return;
		}

		if (target != null) {
			target.clearBackPointerR608To(this);
		}

		if (ControlsBlock != null) {

			m_block_id = ControlsBlock.getBlock_id();
			ControlsBlock = null;
			target.removeRef();
		}
	}

	public static WhileStmt_c getOneACT_WHLOnR608(Block_c[] targets) {
		return getOneACT_WHLOnR608(targets, null);
	}

	public static WhileStmt_c getOneACT_WHLOnR608(Block_c[] targets,
			ClassQueryInterface_c test) {
		WhileStmt_c ret_val = null;
		if (targets != null) {
			for (int i = 0; i < targets.length && ret_val == null; ++i) {
				ret_val = getOneACT_WHLOnR608(targets[i], test);
			}
		}

		return ret_val;
	}

	public static WhileStmt_c getOneACT_WHLOnR608(Block_c target) {
		return getOneACT_WHLOnR608(target, null);
	}

	public static WhileStmt_c getOneACT_WHLOnR608(Block_c target,
			boolean loadComponent) {
		return getOneACT_WHLOnR608(target.getModelRoot(), target, null,
				loadComponent);
	}

	public static WhileStmt_c getOneACT_WHLOnR608(Block_c target,
			ClassQueryInterface_c test) {
		if (target != null) {
			return getOneACT_WHLOnR608(target.getModelRoot(), target, test);
		}
		return null;
	}

	public static WhileStmt_c getOneACT_WHLOnR608(ModelRoot modelRoot,
			Block_c target, ClassQueryInterface_c test) {
		return getOneACT_WHLOnR608(modelRoot, target, test, true);
	}

	public static WhileStmt_c getOneACT_WHLOnR608(ModelRoot modelRoot,
			Block_c target, ClassQueryInterface_c test, boolean loadComponent) {
		return find_getOneACT_WHLOnR608(modelRoot, target, test);
	}
	private static WhileStmt_c find_getOneACT_WHLOnR608(ModelRoot modelRoot,
			Block_c target, ClassQueryInterface_c test) {
		if (target != null) {
			WhileStmt_c source = (WhileStmt_c) target.backPointer_WhileStmt_R608;
			if (source != null && (test == null || test.evaluate(source))) {
				return source;
			}
		}
		// not found
		return null;
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR608(Block_c[] targets) {
		return getManyACT_WHLsOnR608(targets, null);
	}
	public static WhileStmt_c[] getManyACT_WHLsOnR608(Block_c[] targets,
			boolean loadComponent) {
		return getManyACT_WHLsOnR608(targets, null, loadComponent);
	}
	public static WhileStmt_c[] getManyACT_WHLsOnR608(Block_c[] targets,
			ClassQueryInterface_c test) {
		return getManyACT_WHLsOnR608(targets, test, true);
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR608(Block_c[] targets,
			ClassQueryInterface_c test, boolean loadComponent) {

		if (targets == null || targets.length == 0 || targets[0] == null)
			return new WhileStmt_c[0];

		ModelRoot modelRoot = targets[0].getModelRoot();

		InstanceList instances = modelRoot.getInstanceList(WhileStmt_c.class);

		Vector matches = new Vector();
		for (int i = 0; i < targets.length; i++) {
			WhileStmt_c source = (WhileStmt_c) targets[i].backPointer_WhileStmt_R608;
			if (source != null && (test == null || test.evaluate(source))) {
				matches.add(source);
			}
		}
		if (matches.size() > 0) {
			WhileStmt_c[] ret_set = new WhileStmt_c[matches.size()];
			matches.copyInto(ret_set);
			return ret_set;
		} else {
			return new WhileStmt_c[0];
		}
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR608(Block_c target) {
		if (target != null) {
			Block_c[] targetArray = new Block_c[1];
			targetArray[0] = target;
			return getManyACT_WHLsOnR608(targetArray);
		} else {
			WhileStmt_c[] result = new WhileStmt_c[0];
			return result;
		}
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR608(Block_c target,
			boolean loadComponent) {
		if (target != null) {
			Block_c[] targetArray = new Block_c[1];
			targetArray[0] = target;
			return getManyACT_WHLsOnR608(targetArray, loadComponent);
		} else {
			WhileStmt_c[] result = new WhileStmt_c[0];
			return result;
		}
	}

	// referring navigation

	Value_c ContinueResultValue;
	public void relateAcrossR626To(Value_c target) {
		relateAcrossR626To(target, true);
	}
	public void relateAcrossR626To(Value_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (target == ContinueResultValue)
			return; // already related

		if (ContinueResultValue != target) {

			Object oldKey = getInstanceKey();

			if (ContinueResultValue != null) {

				ContinueResultValue.clearBackPointerR626To(this);

				if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == true) { //$NON-NLS-1$
					Ooaofooa.log
							.println(
									ILogger.CONSISTENCY,
									"WhileStmt_c.relateAcrossR626To(Value_c target)",
									"Relate performed across R626 from While Stmt to Value without unrelate of prior instance.");
				}
			}

			ContinueResultValue = target;
			m_value_id = target.getValue_id();
			updateInstanceKey(oldKey, getInstanceKey());
			target.setBackPointerR626To(this);
			target.addRef();
		}
	}
	public void unrelateAcrossR626From(Value_c target) {
		unrelateAcrossR626From(target, true);
	}
	public void unrelateAcrossR626From(Value_c target, boolean notifyChanges) {
		if (target == null)
			return;

		if (ContinueResultValue == null)
			return; // already unrelated

		if (target != ContinueResultValue) {
			Exception e = new Exception();
			e.fillInStackTrace();
			CorePlugin.logError(
					"Tried to unrelate from non-related instance across R626",
					e);
			return;
		}

		if (target != null) {
			target.clearBackPointerR626To(this);
		}

		if (ContinueResultValue != null) {

			m_value_id = ContinueResultValue.getValue_id();
			ContinueResultValue = null;
			target.removeRef();
		}
	}

	public static WhileStmt_c getOneACT_WHLOnR626(Value_c[] targets) {
		return getOneACT_WHLOnR626(targets, null);
	}

	public static WhileStmt_c getOneACT_WHLOnR626(Value_c[] targets,
			ClassQueryInterface_c test) {
		WhileStmt_c ret_val = null;
		if (targets != null) {
			for (int i = 0; i < targets.length && ret_val == null; ++i) {
				ret_val = getOneACT_WHLOnR626(targets[i], test);
			}
		}

		return ret_val;
	}

	public static WhileStmt_c getOneACT_WHLOnR626(Value_c target) {
		return getOneACT_WHLOnR626(target, null);
	}

	public static WhileStmt_c getOneACT_WHLOnR626(Value_c target,
			boolean loadComponent) {
		return getOneACT_WHLOnR626(target.getModelRoot(), target, null,
				loadComponent);
	}

	public static WhileStmt_c getOneACT_WHLOnR626(Value_c target,
			ClassQueryInterface_c test) {
		if (target != null) {
			return getOneACT_WHLOnR626(target.getModelRoot(), target, test);
		}
		return null;
	}

	public static WhileStmt_c getOneACT_WHLOnR626(ModelRoot modelRoot,
			Value_c target, ClassQueryInterface_c test) {
		return getOneACT_WHLOnR626(modelRoot, target, test, true);
	}

	public static WhileStmt_c getOneACT_WHLOnR626(ModelRoot modelRoot,
			Value_c target, ClassQueryInterface_c test, boolean loadComponent) {
		return find_getOneACT_WHLOnR626(modelRoot, target, test);
	}
	private static WhileStmt_c find_getOneACT_WHLOnR626(ModelRoot modelRoot,
			Value_c target, ClassQueryInterface_c test) {
		if (target != null) {
			WhileStmt_c source = (WhileStmt_c) target.backPointer_WhileStmt_R626;
			if (source != null && (test == null || test.evaluate(source))) {
				return source;
			}
		}
		// not found
		return null;
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR626(Value_c[] targets) {
		return getManyACT_WHLsOnR626(targets, null);
	}
	public static WhileStmt_c[] getManyACT_WHLsOnR626(Value_c[] targets,
			boolean loadComponent) {
		return getManyACT_WHLsOnR626(targets, null, loadComponent);
	}
	public static WhileStmt_c[] getManyACT_WHLsOnR626(Value_c[] targets,
			ClassQueryInterface_c test) {
		return getManyACT_WHLsOnR626(targets, test, true);
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR626(Value_c[] targets,
			ClassQueryInterface_c test, boolean loadComponent) {

		if (targets == null || targets.length == 0 || targets[0] == null)
			return new WhileStmt_c[0];

		ModelRoot modelRoot = targets[0].getModelRoot();

		InstanceList instances = modelRoot.getInstanceList(WhileStmt_c.class);

		Vector matches = new Vector();
		for (int i = 0; i < targets.length; i++) {
			WhileStmt_c source = (WhileStmt_c) targets[i].backPointer_WhileStmt_R626;
			if (source != null && (test == null || test.evaluate(source))) {
				matches.add(source);
			}
		}
		if (matches.size() > 0) {
			WhileStmt_c[] ret_set = new WhileStmt_c[matches.size()];
			matches.copyInto(ret_set);
			return ret_set;
		} else {
			return new WhileStmt_c[0];
		}
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR626(Value_c target) {
		if (target != null) {
			Value_c[] targetArray = new Value_c[1];
			targetArray[0] = target;
			return getManyACT_WHLsOnR626(targetArray);
		} else {
			WhileStmt_c[] result = new WhileStmt_c[0];
			return result;
		}
	}

	public static WhileStmt_c[] getManyACT_WHLsOnR626(Value_c target,
			boolean loadComponent) {
		if (target != null) {
			Value_c[] targetArray = new Value_c[1];
			targetArray[0] = target;
			return getManyACT_WHLsOnR626(targetArray, loadComponent);
		} else {
			WhileStmt_c[] result = new WhileStmt_c[0];
			return result;
		}
	}

	public void batchRelate(ModelRoot modelRoot, boolean notifyChanges,
			boolean searchAllRoots) {
		batchRelate(modelRoot, false, notifyChanges, searchAllRoots);
	}

	public void batchRelate(ModelRoot modelRoot, boolean relateProxies,
			boolean notifyChanges, boolean searchAllRoots) {
		InstanceList instances = null;
		ModelRoot baseRoot = modelRoot;

		// R603
		Statement_c relInst56074 = (Statement_c) baseRoot.getInstanceList(
				Statement_c.class).get(new Object[]{m_statement_id});
		// if there was no local element, check for any global elements
		// failing that proceed to check other model roots
		if (relInst56074 == null) {
			relInst56074 = (Statement_c) Ooaofooa.getDefaultInstance()
					.getInstanceList(Statement_c.class)
					.get(new Object[]{m_statement_id});
		}
		if (relInst56074 == null && searchAllRoots && !baseRoot.isCompareRoot()) {
			Ooaofooa[] roots = Ooaofooa.getInstances();
			for (int i = 0; i < roots.length; i++) {
				if (roots[i].isCompareRoot()) {
					// never use elements from any compare root
					continue;
				}
				relInst56074 = (Statement_c) roots[i].getInstanceList(
						Statement_c.class).get(new Object[]{m_statement_id});
				if (relInst56074 != null)
					break;
			}
		}
		//synchronized
		if (relInst56074 != null) {
			if (relateProxies || !isProxy()
					|| (inSameComponent(this, relInst56074) && !isProxy())) {
				relInst56074.relateAcrossR603To(this, notifyChanges);
			}
		}

		if (ControlsBlock == null) {
			// R608
			Block_c relInst56075 = (Block_c) baseRoot.getInstanceList(
					Block_c.class).get(new Object[]{m_block_id});
			// if there was no local element, check for any global elements
			// failing that proceed to check other model roots
			if (relInst56075 == null) {
				relInst56075 = (Block_c) Ooaofooa.getDefaultInstance()
						.getInstanceList(Block_c.class)
						.get(new Object[]{m_block_id});
			}
			if (relInst56075 == null && searchAllRoots
					&& !baseRoot.isCompareRoot()) {
				Ooaofooa[] roots = Ooaofooa.getInstances();
				for (int i = 0; i < roots.length; i++) {
					if (roots[i].isCompareRoot()) {
						// never use elements from any compare root
						continue;
					}
					relInst56075 = (Block_c) roots[i].getInstanceList(
							Block_c.class).get(new Object[]{m_block_id});
					if (relInst56075 != null)
						break;
				}
			}
			//synchronized
			if (relInst56075 != null) {
				if (relateProxies || !isProxy()
						|| (inSameComponent(this, relInst56075) && !isProxy())) {
					relInst56075.relateAcrossR608To(this, notifyChanges);
				}
			}
		}

		if (ContinueResultValue == null) {
			// R626
			Value_c relInst56076 = (Value_c) baseRoot.getInstanceList(
					Value_c.class).get(new Object[]{m_value_id});
			// if there was no local element, check for any global elements
			// failing that proceed to check other model roots
			if (relInst56076 == null) {
				relInst56076 = (Value_c) Ooaofooa.getDefaultInstance()
						.getInstanceList(Value_c.class)
						.get(new Object[]{m_value_id});
			}
			if (relInst56076 == null && searchAllRoots
					&& !baseRoot.isCompareRoot()) {
				Ooaofooa[] roots = Ooaofooa.getInstances();
				for (int i = 0; i < roots.length; i++) {
					if (roots[i].isCompareRoot()) {
						// never use elements from any compare root
						continue;
					}
					relInst56076 = (Value_c) roots[i].getInstanceList(
							Value_c.class).get(new Object[]{m_value_id});
					if (relInst56076 != null)
						break;
				}
			}
			//synchronized
			if (relInst56076 != null) {
				if (relateProxies || !isProxy()
						|| (inSameComponent(this, relInst56076) && !isProxy())) {
					relInst56076.relateAcrossR626To(this, notifyChanges);
				}
			}
		}

	}
	public void batchUnrelate(boolean notifyChanges) {
		NonRootModelElement inst = null;
		// R603
		// ACT_SMT
		inst = IsSupertypeStatement;
		unrelateAcrossR603From(IsSupertypeStatement, notifyChanges);
		if (inst != null) {
			inst.removeRef();
		}
		// R608
		// ACT_BLK
		inst = ControlsBlock;
		unrelateAcrossR608From(ControlsBlock, notifyChanges);
		if (inst != null) {
			inst.removeRef();
		}
		// R626
		// V_VAL
		inst = ContinueResultValue;
		unrelateAcrossR626From(ContinueResultValue, notifyChanges);
		if (inst != null) {
			inst.removeRef();
		}
	}
	public static void batchRelateAll(ModelRoot modelRoot,
			boolean notifyChanges, boolean searchAllRoots) {
		batchRelateAll(modelRoot, notifyChanges, searchAllRoots, false);
	}
	public static void batchRelateAll(ModelRoot modelRoot, boolean notifyChanges, boolean searchAllRoots, boolean relateProxies)
  {
	InstanceList instances = modelRoot.getInstanceList(WhileStmt_c.class);
    synchronized(instances) {
        Iterator<NonRootModelElement> cursor = instances.iterator() ;
    	while (cursor.hasNext())
	    {
            final WhileStmt_c inst = (WhileStmt_c)cursor.next() ;
	        inst.batchRelate(modelRoot, relateProxies, notifyChanges, searchAllRoots );
	    }
	}
  }
	public static void clearInstances(ModelRoot modelRoot) {
		InstanceList instances = modelRoot.getInstanceList(WhileStmt_c.class);
		synchronized (instances) {
			for (int i = instances.size() - 1; i >= 0; i--) {
				((NonRootModelElement) instances.get(i)).delete_unchecked();
			}

		}
	}

	public static WhileStmt_c WhileStmtInstance(ModelRoot modelRoot,
			ClassQueryInterface_c test, boolean loadComponent) {
		WhileStmt_c result = findWhileStmtInstance(modelRoot, test,
				loadComponent);
		return result;
	}
	private static WhileStmt_c findWhileStmtInstance(ModelRoot modelRoot,
			ClassQueryInterface_c test, boolean loadComponent) {
		InstanceList instances = modelRoot.getInstanceList(WhileStmt_c.class);
		synchronized (instances) {
			for (int i = 0; i < instances.size(); ++i) {
				WhileStmt_c x = (WhileStmt_c) instances.get(i);
				if (test == null || test.evaluate(x)) {
					return x;
				}
			}
		}
		return null;
	}
	public static WhileStmt_c WhileStmtInstance(ModelRoot modelRoot,
			ClassQueryInterface_c test) {
		return WhileStmtInstance(modelRoot, test, true);
	}

	public static WhileStmt_c WhileStmtInstance(ModelRoot modelRoot) {
		return WhileStmtInstance(modelRoot, null, true);
	}

	public static WhileStmt_c[] WhileStmtInstances(ModelRoot modelRoot,
			ClassQueryInterface_c test, boolean loadComponent) {
		InstanceList instances = modelRoot.getInstanceList(WhileStmt_c.class);
		Vector matches = new Vector();
		synchronized (instances) {
			for (int i = 0; i < instances.size(); ++i) {
				WhileStmt_c x = (WhileStmt_c) instances.get(i);
				if (test == null || test.evaluate(x)) {
					matches.add(x);
				}
			}
			if (matches.size() > 0) {
				WhileStmt_c[] ret_set = new WhileStmt_c[matches.size()];
				matches.copyInto(ret_set);
				return ret_set;
			} else {
				return new WhileStmt_c[0];
			}
		}
	}
	public static WhileStmt_c[] WhileStmtInstances(ModelRoot modelRoot,
			ClassQueryInterface_c test) {
		return WhileStmtInstances(modelRoot, test, true);
	}
	public static WhileStmt_c[] WhileStmtInstances(ModelRoot modelRoot) {
		return WhileStmtInstances(modelRoot, null, true);
	}

	public boolean delete() {
		boolean result = super.delete();
		boolean delete_error = false;
		String errorMsg = "The following relationships were not torn down by the While Stmt.dispose call: ";
		Statement_c testR603Inst3 = Statement_c
				.getOneACT_SMTOnR603(this, false);

		if (testR603Inst3 != null) {
			delete_error = true;
			errorMsg = errorMsg + "603 ";
		}
		Block_c testR608Inst = Block_c.getOneACT_BLKOnR608(this, false);

		if (testR608Inst != null) {
			delete_error = true;
			errorMsg = errorMsg + "608 ";
		}
		Value_c testR626Inst = Value_c.getOneV_VALOnR626(this, false);

		if (testR626Inst != null) {
			delete_error = true;
			errorMsg = errorMsg + "626 ";
		}
		if (delete_error == true) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log.println(ILogger.DELETE, "While Stmt", errorMsg);
			} else {
				Exception e = new Exception();
				e.fillInStackTrace();
				CorePlugin.logError(errorMsg, e);
			}
		}
		return result;
	}

	// end declare instance pool

	// declare attribute accessors
	public boolean isUUID(String attributeName) {
		if (attributeName.equals("statement_id")) {
			return true;
		}
		if (attributeName.equals("value_id")) {
			return true;
		}
		if (attributeName.equals("block_id")) {
			return true;
		}
		return false;
	}
	// declare attribute accessors
	public long getStatement_idLongBased() {
		if (IsSupertypeStatement != null) {
			return IsSupertypeStatement.getStatement_idLongBased();
		}
		return 0;
	}
	public java.util.UUID getStatement_id() {
		if (IsSupertypeStatement != null) {
			return IsSupertypeStatement.getStatement_id();
		}
		return IdAssigner.NULL_UUID;
	}

	public boolean hasSuperType() {
		return (IsSupertypeStatement != null);

	}

	public java.util.UUID getStatement_idCachedValue() {
		if (!IdAssigner.NULL_UUID.equals(m_statement_id))
			return m_statement_id;
		else
			return getStatement_id();
	}

	public void setStatement_id(java.util.UUID newValue) {
		m_statement_id = IdAssigner.preprocessUUID(newValue);
	}
	public long getValue_idLongBased() {
		if (ContinueResultValue != null) {
			return ContinueResultValue.getValue_idLongBased();
		}
		return 0;
	}
	public java.util.UUID getValue_id() {
		if (ContinueResultValue != null) {
			return ContinueResultValue.getValue_id();
		}
		return IdAssigner.NULL_UUID;
	}

	public java.util.UUID getValue_idCachedValue() {
		if (!IdAssigner.NULL_UUID.equals(m_value_id))
			return m_value_id;
		else
			return getValue_id();
	}

	public void setValue_id(java.util.UUID newValue) {
		m_value_id = IdAssigner.preprocessUUID(newValue);
	}
	public long getBlock_idLongBased() {
		if (ControlsBlock != null) {
			return ControlsBlock.getBlock_idLongBased();
		}
		return 0;
	}
	public java.util.UUID getBlock_id() {
		if (ControlsBlock != null) {
			return ControlsBlock.getBlock_id();
		}
		return IdAssigner.NULL_UUID;
	}

	public java.util.UUID getBlock_idCachedValue() {
		if (!IdAssigner.NULL_UUID.equals(m_block_id))
			return m_block_id;
		else
			return getBlock_id();
	}

	public void setBlock_id(java.util.UUID newValue) {
		m_block_id = IdAssigner.preprocessUUID(newValue);
	}
	// end declare accessors
	public static void checkClassConsistency(ModelRoot modelRoot) {
		Ooaofooa.log.println(ILogger.OPERATION, "While Stmt", //$NON-NLS-1$
				" Operation entered: While Stmt::checkClassConsistency"); //$NON-NLS-1$
		if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) { //$NON-NLS-1$
			return;
		}
		WhileStmt_c[] objs = WhileStmt_c.WhileStmtInstances(modelRoot, null,
				false);

		for (int i = 0; i < objs.length; i++) {
			objs[i].checkConsistency();
		}
	}
	public boolean checkConsistency() {
		Ooaofooa.log.println(ILogger.OPERATION, "While Stmt", //$NON-NLS-1$
				" Operation entered: While Stmt::checkConsistency"); //$NON-NLS-1$
		if (Boolean.valueOf(System.getenv("PTC_MCC_ENABLED")) == false) { //$NON-NLS-1$
			return true;
		}
		ModelRoot modelRoot = getModelRoot();
		boolean retval = true;
		class WhileStmt_c_test56078_c implements ClassQueryInterface_c {
			WhileStmt_c_test56078_c(java.util.UUID p56079) {
				m_p56079 = p56079;
			}
			private java.util.UUID m_p56079;
			public boolean evaluate(Object candidate) {
				WhileStmt_c selected = (WhileStmt_c) candidate;
				boolean retval = false;
				retval = (selected.getStatement_id().equals(m_p56079));
				return retval;
			}
		}

		WhileStmt_c[] objs56077 = WhileStmt_c.WhileStmtInstances(modelRoot,
				new WhileStmt_c_test56078_c(getStatement_id()));

		if (((objs56077.length) == 0)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(ILogger.CONSISTENCY,
								"While Stmt", //$NON-NLS-1$
								"Consistency: Object: While Stmt: Cardinality of an identifier is zero. " //$NON-NLS-1$
										+ "Actual Value: " + Integer.toString(objs56077.length)); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin.logError(
						"Consistency: Object: While Stmt: Cardinality of an identifier is zero. " //$NON-NLS-1$ 
								+ "Actual Value: " //$NON-NLS-1$
								+ Integer.toString(objs56077.length), e);
			}
			retval = false;

		}

		if (((objs56077.length) > 1)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(ILogger.CONSISTENCY,
								"While Stmt", //$NON-NLS-1$
								"Consistency: Object: While Stmt: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$
										+ "Actual Value: " //$NON-NLS-1$ 
										+ Integer.toString(objs56077.length)
										+ " Statement_ID: " + "Not Printable"); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: While Stmt: Cardinality of an identifier is greater than 1. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs56077.length)
										+ " Statement_ID: " + "Not Printable", e); //$NON-NLS-1$
			}
			retval = false;

		}

		// While Stmt is a subtype in association: rel.Numb = 603
		// The supertype class is: Statement
		class Statement_c_test56083_c implements ClassQueryInterface_c {
			Statement_c_test56083_c(java.util.UUID p56084) {
				m_p56084 = p56084;
			}
			private java.util.UUID m_p56084;
			public boolean evaluate(Object candidate) {
				Statement_c selected = (Statement_c) candidate;
				boolean retval = false;
				retval = (selected.getStatement_id().equals(m_p56084));
				return retval;
			}
		}

		Statement_c[] objs56082 = Statement_c.StatementInstances(modelRoot,
				new Statement_c_test56083_c(getStatement_id()));

		if (((objs56082.length) != 1)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(ILogger.CONSISTENCY,
								"While Stmt", //$NON-NLS-1$
								"Consistency: Object: While Stmt: Association: 603: Cardinality of a supertype is not equal to 1. " //$NON-NLS-1$
										+ "Actual Value: " + Integer.toString(objs56082.length)); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: While Stmt: Association: 603: Cardinality of a supertype is not equal to 1. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs56082.length), e);
			}
			retval = false;

		}

		// While Stmt is a referring class in association: rel.Numb = 626
		// The participating class is: Value
		class Value_c_test56086_c implements ClassQueryInterface_c {
			Value_c_test56086_c(java.util.UUID p56087) {
				m_p56087 = p56087;
			}
			private java.util.UUID m_p56087;
			public boolean evaluate(Object candidate) {
				Value_c selected = (Value_c) candidate;
				boolean retval = false;
				retval = (selected.getValue_id().equals(m_p56087));
				return retval;
			}
		}

		Value_c[] objs56085 = Value_c.ValueInstances(modelRoot,
				new Value_c_test56086_c(getValue_id()));

		// The participant is unconditional
		// The multiplicity of the participant is one
		if (((objs56085.length) != 1)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(ILogger.CONSISTENCY,
								"While Stmt", //$NON-NLS-1$
								"Consistency: Object: While Stmt: Association: 626: Cardinality of a participant is not equal to 1. " //$NON-NLS-1$
										+ "Actual Value: " //$NON-NLS-1$ 
										+ Integer.toString(objs56085.length)
										+ " Value_ID: " + "Not Printable"); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: While Stmt: Association: 626: Cardinality of a participant is not equal to 1. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs56085.length)
										+ " Value_ID: " + "Not Printable", e); //$NON-NLS-1$
			}
			retval = false;

		}

		// While Stmt is a referring class in association: rel.Numb = 608
		// The participating class is: Block
		class Block_c_test56089_c implements ClassQueryInterface_c {
			Block_c_test56089_c(java.util.UUID p56090) {
				m_p56090 = p56090;
			}
			private java.util.UUID m_p56090;
			public boolean evaluate(Object candidate) {
				Block_c selected = (Block_c) candidate;
				boolean retval = false;
				retval = (selected.getBlock_id().equals(m_p56090));
				return retval;
			}
		}

		Block_c[] objs56088 = Block_c.BlockInstances(modelRoot,
				new Block_c_test56089_c(getBlock_id()));

		// The participant is unconditional
		// The multiplicity of the participant is one
		if (((objs56088.length) != 1)) {

			if (CorePlugin.getDefault().isDebugging()) {
				Ooaofooa.log
						.println(ILogger.CONSISTENCY,
								"While Stmt", //$NON-NLS-1$
								"Consistency: Object: While Stmt: Association: 608: Cardinality of a participant is not equal to 1. " //$NON-NLS-1$
										+ "Actual Value: " //$NON-NLS-1$ 
										+ Integer.toString(objs56088.length)
										+ " Block_ID: " + "Not Printable"); //$NON-NLS-1$
			} else {
				Exception e = new Exception();
				CorePlugin
						.logError(
								"Consistency: Object: While Stmt: Association: 608: Cardinality of a participant is not equal to 1. " //$NON-NLS-1$ 
										+ "Actual Value: " //$NON-NLS-1$
										+ Integer.toString(objs56088.length)
										+ " Block_ID: " + "Not Printable", e); //$NON-NLS-1$
			}
			retval = false;

		}

		return retval;
	}

	// declare transform functions
	public void Dispose() {
		Ooaofooa.log.println(ILogger.OPERATION, "While Stmt",
				" Operation entered: WhileStmt::Dispose");
		final ModelRoot modelRoot = getModelRoot();
		Block_c v_blk = Block_c.getOneACT_BLKOnR608(this);

		if (((v_blk != null))) {

			this.unrelateAcrossR608From(v_blk);

			if (v_blk != null) {
				v_blk.Dispose();
			} else {
				Throwable t = new Throwable();
				t.fillInStackTrace();
				CorePlugin
						.logError(
								"Attempted to call an operation on a null instance.",
								t);
			}

		}

		Value_c v_val = Value_c.getOneV_VALOnR626(this);

		if (((v_val != null))) {

			this.unrelateAcrossR626From(v_val);

			if (v_val != null) {
				v_val.Dispose();
			} else {
				Throwable t = new Throwable();
				t.fillInStackTrace();
				CorePlugin
						.logError(
								"Attempted to call an operation on a null instance.",
								t);
			}

		}

		delete();

	} // End dispose
	public void Execute(final java.util.UUID p_Stack_frame_id) {
		Ooaofooa.log.println(ILogger.OPERATION, "While Stmt",
				" Operation entered: WhileStmt::Execute");
		final ModelRoot modelRoot = getModelRoot();

	} // End execute

	// end transform functions

	public Object getAdapter(Class adapter) {
		Object superAdapter = super.getAdapter(adapter);
		if (superAdapter != null) {
			return superAdapter;
		}
		return null;
	}
} // end While Stmt
