//======================================================================
//
// File: FunctionParameterS_SPARMPropertySource.java
//
// WARNING:      Do not edit this generated file
// Generated by: arc/BuildPropertySource.arc
// Version:      $Revision: 1.66 $
//
// (c) Copyright 2006-2014 by Mentor Graphics Corp.  All rights reserved.
//
//======================================================================

package com.mentor.nucleus.bp.ui.properties;
import java.text.Collator;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Vector;

import org.eclipse.ui.views.properties.*;

import com.mentor.nucleus.bp.core.*;
import com.mentor.nucleus.bp.core.common.*;
import com.mentor.nucleus.bp.core.sorter.MetadataSortingManager;
import com.mentor.nucleus.bp.core.ui.cells.editors.*;
import com.mentor.nucleus.bp.core.util.DimensionsUtil;

public class FunctionParameterS_SPARMPropertySource implements IPropertySource {
	private FunctionParameter_c m_inst;
	private String[] m_DataTypeType;
	private PropertyDescriptor[] m_propertyDescriptors;
	private String[] By_Ref_vals = {"By Value", "By Reference"};
	MetadataSortingManager sorter = MetadataSortingManager.createDefault();

	public FunctionParameterS_SPARMPropertySource(FunctionParameter_c inst) {
		m_inst = inst;
	}
	/* (non-Javadoc)
	 * @see org.eclipse.ui.views.properties.IPropertySource#getEditableValue()
	 */
	public Object getEditableValue() {
		return this;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.ui.views.properties.IPropertySource#isPropertySet(java.lang.Object)
	 */
	public boolean isPropertySet(Object id) {
		return false;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.ui.views.properties.IPropertySource#resetPropertyValue(java.lang.Object)
	 */
	public void resetPropertyValue(Object id) {
		// do nothing
	}

	public String toString() {
		return m_inst.getName();
	}

	/* (non-Javadoc)
	 * @see org.eclipse.ui.views.properties.IPropertySource#getPropertyDescriptors()
	 */
	public IPropertyDescriptor[] getPropertyDescriptors() {
		if (m_inst == null || m_inst.isOrphaned())
			return new IPropertyDescriptor[0];
		int num_children = 0;
		if (m_propertyDescriptors == null
				|| 5 + num_children != m_propertyDescriptors.length) {
			m_propertyDescriptors = new PropertyDescriptor[5 + num_children];
			boolean readonly = false;

			m_propertyDescriptors[0] = new TextPropertyDescriptor("Name",
					"Parameter Name");
			m_propertyDescriptors[0]
					.setValidator(new ModelElementNameValidator(m_inst));
			m_propertyDescriptors[0]
					.setCategory(BridgepointPropertySheetPage.basicCategoryName);
			m_propertyDescriptors[1] = new EnumPropertyDescriptor("By_Ref",
					"By Reference Indicator", By_Ref_vals, readonly);
			m_propertyDescriptors[1]
					.setCategory(BridgepointPropertySheetPage.basicCategoryName);
			m_propertyDescriptors[2] = new DimensionsPropertyDescriptor(
					"Dimensions", "Array Dimensions", readonly);
			m_propertyDescriptors[2].setValidator(new DimensionsValidator(
					(NonRootModelElement) m_inst));
			m_propertyDescriptors[2].setDescription(DimensionsValidator
					.getDimensionsHelpText(readonly));
			m_propertyDescriptors[2]
					.setCategory(BridgepointPropertySheetPage.basicCategoryName);
			m_propertyDescriptors[3] = new DescriptionPropertyDescriptor(
					"Descrip", "Description", m_inst);
			m_propertyDescriptors[3]
					.setCategory(BridgepointPropertySheetPage.basicCategoryName);

			int d_index = 4;
			// create combobox descriptor for Data Type
			DataType_c[] set4 = new DataType_c[0];
			DataType_c[] set4_2 = new DataType_c[0];
			// Note that datatypes our handled by the dt chooser dialog
			List list5 = new ArrayList(set4.length + set4_2.length);
			for (int i = 0; i < set4.length; ++i) {
				if (m_inst.Isallowedtype(set4[i].getName())) {
					list5.add(set4[i].getName());
				}
			}
			Collections.sort(list5, new Comparator() {
				Collator coll = Collator.getInstance(Locale.getDefault());
				public int compare(Object a, Object b) {
					return coll.compare((String) a, (String) b);
				}
			});
			m_DataTypeType = new String[list5.size()];
			for (int i = 0; i < list5.size(); ++i) {
				m_DataTypeType[i] = (String) list5.get(i);
			}
			m_propertyDescriptors[d_index] = new ChooserPropertyDescriptor(
					"DataType",
					"Type",
					m_inst,
					"com.mentor.nucleus.bp.core.ui.actions.SetTypeOnS_SPARMAction",
					readonly);
			m_propertyDescriptors[d_index]
					.setCategory(BridgepointPropertySheetPage.basicCategoryName);
			++d_index;
		}
		return m_propertyDescriptors;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.ui.views.properties.IPropertySource#getPropertyValue(java.lang.Object)
	 */
	public Object getPropertyValue(Object id) {
		if (m_inst.isOrphaned()) {
			return "";
		}
		if (id.equals("Name")) {
			return m_inst.getName();
		} else if (id.equals("By_Ref")) {
			return By_Ref_vals[m_inst.getBy_ref()];
		} else if (id.equals("Dimensions")) {
			return m_inst.getDimensions();
		} else if (id.equals("Descrip")) {
			return m_inst.getDescrip().replace('\n', '/');
		}
		int d_index = 4;
		// getPropertyValue for combobox for Data Type
		if (id.equals("DataType")) {
			DataType_c val = DataType_c
					.getOneS_DTOnR26((FunctionParameter_c) m_inst);

			if (val != null)
				return val.getName();
		}
		++d_index;
		return null;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.ui.views.properties.IPropertySource#setPropertyValue(java.lang.Object, java.lang.Object)
	 */
	public void setPropertyValue(Object id, Object value) {
		boolean value_changed = false;
		String trans_name = "";
		Transaction tr = null;
		Ooaofooa modelRoot = (Ooaofooa) m_inst.getModelRoot();
		TransactionManager tm = TransactionManager.getSingleton();
		try {
			if (id.equals("Name")) {
				if (!value.toString().equals(m_inst.getName())) {
					trans_name = "Change in property: 'Name' of Function Parameter";//$NON-NLS-1$
					tr = tm.startTransaction(trans_name,
							Ooaofooa.getDefaultInstance());
					value_changed = true;
					m_inst.setName(value.toString());
				}
			} else if (id.equals("By_Ref")) {
				int new_val = Integer.parseInt(value.toString());
				if (new_val != m_inst.getBy_ref()) {
					trans_name = "Change in property: 'By_Ref' of Function Parameter";//$NON-NLS-1$
					tr = tm.startTransaction(trans_name,
							Ooaofooa.getDefaultInstance());
					value_changed = true;
					m_inst.setBy_ref(new_val);
				}
			} else if (id.equals("Dimensions")) {
				if (!value.toString().equals(m_inst.getDimensions())) {
					trans_name = "Change in property: 'Dimensions' of Function Parameter";//$NON-NLS-1$
					tr = tm.startTransaction(trans_name,
							Ooaofooa.getDefaultInstance());
					value_changed = true;
					Vector dims = DimensionsUtil.getDimensionsData(
							value.toString(), m_inst);
					if (dims.size() > 0) {
						for (int i = 0; i < dims.size(); i++) {
							int numElements = ((Integer) dims.get(i))
									.intValue();
							m_inst.Resizedimensions(i, numElements, dims.size());
						}
					} else {
						m_inst.Resizedimensions(0, 0, 0);
					}
					m_inst.setDimensions(value.toString());
				}
			} else if (id.equals("Descrip")) {
				if (!value.toString().equals(m_inst.getDescrip())) {
					trans_name = "Change in property: 'Descrip' of Function Parameter";//$NON-NLS-1$
					tr = tm.startTransaction(trans_name,
							Ooaofooa.getDefaultInstance());
					value_changed = true;
					m_inst.setDescrip(value.toString());
				}
			}

			int d_index = 4;
			if (id.equals("DataType")) {
				DataType_c val = DataType_c
						.getOneS_DTOnR26((FunctionParameter_c) m_inst);

				if (!value.equals(val.getName())) {
					DataType_c[] set6_1 = new DataType_c[0];
					DataType_c[] set6_2 = new DataType_c[0];
					if (m_inst.isInGenericPackage()) {
						Package_c pkg = m_inst.getFirstParentPackage();
						Component_c component = m_inst
								.getFirstParentComponent();
						if ((pkg != null)) {
							pkg.Clearscope();
							pkg.Collectvisibleelementsforname(false,
									Gd_c.Null_unique_id(), false, "",
									pkg.getPackage_id(),
									Elementtypeconstants_c.DATATYPE);

							class SearchResultSet_test24870_c
									implements
										ClassQueryInterface_c {
								public boolean evaluate(Object candidate) {
									SearchResultSet_c selected = (SearchResultSet_c) candidate;
									return selected.getName().equals("")
											&& selected.getType() == Elementtypeconstants_c.DATATYPE;
								}
							}
							SearchResultSet_c v_resultSet = SearchResultSet_c
									.getOnePE_SRSOnR8005(pkg,
											new SearchResultSet_test24870_c());

							set6_2 = DataType_c
									.getManyS_DTsOnR8001(PackageableElement_c
											.getManyPE_PEsOnR8002(ElementVisibility_c
													.getManyPE_VISsOnR8006(v_resultSet)));
						} else {
							if (component != null) {
								component.Clearscope();
								component.Collectvisibleelementsforname(false,
										Gd_c.Null_unique_id(), "",
										component.getId(),
										Elementtypeconstants_c.DATATYPE);

								class ComponentResultSet_test24870_c
										implements
											ClassQueryInterface_c {
									public boolean evaluate(Object candidate) {
										ComponentResultSet_c selected = (ComponentResultSet_c) candidate;
										return selected.getName().equals("")
												&& selected.getType() == Elementtypeconstants_c.DATATYPE;
									}
								}
								ComponentResultSet_c v_resultSet = ComponentResultSet_c
										.getOnePE_CRSOnR8007(
												component,
												new ComponentResultSet_test24870_c());

								set6_2 = DataType_c
										.getManyS_DTsOnR8001(PackageableElement_c
												.getManyPE_PEsOnR8004(ComponentVisibility_c
														.getManyPE_CVSsOnR8008(v_resultSet)));

							} else {
								// only throw an error the the element owning
								// this property source, are expected to not
								// have a package or component (the cases that
								// are not are UDTs that are built in)  Note that
								// the tool will behave properly, as the field
								// for these are read-only.
								if (!m_inst.selfIsCoreDataType()) {
									Throwable t = new Throwable();
									t.fillInStackTrace();
									CorePlugin
											.logError(
													"Attempted to call an operation on a null instance.",
													t);
								}
							}

						}
					}

					else {
						Domain_c domain = Domain_c
								.getOneS_DOMOnR23(Function_c
										.getOneS_SYNCOnR24((FunctionParameter_c) m_inst));
						set6_1 = DataType_c.getManyS_DTsOnR14(domain);
						set6_2 = DataType_c
								.getManyS_DTsOnR4401(SystemDatatypeInPackage_c.getManySLD_SDINPsOnR4402(SystemModel_c
										.getManyS_SYSsOnR4606(ComponentPackage_c
												.getManyCP_CPsOnR4608(Component_c
														.getManyC_CsOnR4204(DomainAsComponent_c
																.getManyCN_DCsOnR4204(domain))))));
					} // end isInGenericPackage
						// copy the system level data types into the
						// domain level data types array
					DataType_c[] set6_3 = new DataType_c[0];
					if (((SystemModel_c) m_inst.getRoot()).getUseglobals() == true) {
						set6_3 = DataType_c
								.getManyS_DTsOnR8001(PackageableElement_c
										.getManyPE_PEsOnR9100(GlobalElementInSystem_c
												.getManyG_EISsOnR9100((SystemModel_c) this.m_inst
														.getRoot())));
					}
					DataType_c[] set6 = new DataType_c[set6_1.length
							+ set6_2.length + +set6_3.length];
					System.arraycopy(set6_1, 0, set6, 0, set6_1.length);
					System.arraycopy(set6_2, 0, set6, set6_1.length,
							set6_2.length);
					System.arraycopy(set6_3, 0, set6, set6_1.length
							+ set6_2.length, set6_3.length);
					for (int i = 0; i < set6.length; ++i) {
						if (value.equals(set6[i].getName())) {
							trans_name = "Change in property: 'Type' of Function Parameter"; //$NON-NLS-1$
							tr = tm.startTransaction(trans_name,
									Ooaofooa.getDefaultInstance());
							m_inst.unrelateAcrossR26From(val);
							m_inst.relateAcrossR26To(set6[i]);
							value_changed = true;
							break;
						}
					}
				}
			}
			++d_index;

			// catch all exceptions and cancel the transaction
		} catch (Exception e) {
			// this can be null if there was
			// an exception starting the
			// transaction
			if (tr != null) {
				tm.cancelTransaction(tr, e);
				tr = null;
			}
			CorePlugin.logError("Transaction: " + trans_name
					+ " could not complete", e);
		}
		if (tr != null) {
			if (value_changed)
				tm.endTransaction(tr);
			else
				tm.cancelTransaction(tr);
		}
	}
}
