package com.mentor.nucleus.bp.ui.explorer.adapters;
//======================================================================
//
// File: com/mentor/nucleus/bp/ui/explorer/adapters/OperationsAdapter.java
//
// WARNING:      Do not edit this generated file
// Generated by: arc/create_adapters.inc
// Version:      $Revision: 1.31 $
//
// (c) Copyright 2006-2014 by Mentor Graphics Corp.  All rights reserved.
//
//======================================================================
//
// This class is responsible for decoupling the client model entity
// class Operation_c from the tree viewer and the hierarchy
// it imposes.
//
import java.util.ArrayList;
import java.util.List;

import org.eclipse.jface.viewers.ITreeContentProvider;
import org.eclipse.jface.viewers.Viewer;
import com.mentor.nucleus.bp.core.*;

import com.mentor.nucleus.bp.ui.explorer.*;
import com.mentor.nucleus.bp.core.sorter.OperationParameter_cSorter;
/**
 * This file adapts the meta-model entity; 'Operation_c'
 * so that it works with the Eclipse JFace user interface components.
 * <p>
 * Do not edit this class, it was created using the Mentor 
 * Graphics MC-Java code generator product.
 * </p>
 */
public class OperationsAdapter implements ITreeContentProvider {
	static OperationsAdapter operationsadapter = null;
	/**
	 * Returns the adapters singleton instance. If this
	 * is the first time, the instance is created.
	 */
	public static OperationsAdapter getInstance() {
		if (operationsadapter == null) {
			operationsadapter = new OperationsAdapter();
		}
		return operationsadapter;
	}
	/**
	 * @see IContentProvider#inputChanged(Viewer, Object, Object)
	 * Called when the tree's input has been changed
	 */
	public void inputChanged(Viewer viewer, Object oldInput, Object newInput) {
		// Nothing to do
	}
	/**
	 * @see IContentProvider#dispose()
	 * Called when this viewer is no longer needed
	 */
	public void dispose() {
		// Nothing to dispose
	}
	/**
	 * @see ITreeContentProvider#getParent(Object)
	 * Returns the parent of this node
	 */
	public Object getParent(Object arg) {
		ModelClass_c result9 = ModelClass_c
				.getOneO_OBJOnR115((Operation_c) arg);
		if (result9 != null) {
			return result9;
		}
		return null;
	}
	/**
	 * @see IStructuredContentProvider#getElements(Object)
	 * Returns the elements below this node
	 */
	public Object[] getElements(Object arg) {
		return getChildren(arg);
	}

	/**
	 * @see ITreeContentProvider#getChildren(Object)
	 * Returns the children of this node
	 */
	public Object[] getChildren(Object arg) {
		int resultSize = 0;
		OperationParameter_c[] operationparameters_117_1 = OperationParameter_c
				.getManyO_TPARMsOnR117((Operation_c) arg);

		resultSize += operationparameters_117_1.length;

		Object[] result = new Object[resultSize];
		int count = 0;
		OperationParameter_cSorter sorterO_TPARM = new OperationParameter_cSorter();
		sorterO_TPARM.sort(operationparameters_117_1);
		for (int i = 0; i < operationparameters_117_1.length; i++) {
			result[count] = operationparameters_117_1[i];
			count++;
		}
		return result;
	}
	/**
	 * @see ITreeContentProvider#hasChildren(Object)
	 * Returns true if this node has any children
	 */
	public boolean hasChildren(Object arg) {
		OperationParameter_c[] operationparameters_117_1 = OperationParameter_c
				.getManyO_TPARMsOnR117((Operation_c) arg);

		if (operationparameters_117_1.length > 0)
			return true;
		return false;
	}
}
